// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



public partial class MainWindow {
    
    private Gtk.Action File;
    
    private Gtk.Action Edit;
    
    private Gtk.Action View;
    
    private Gtk.Action Help;
    
    private Gtk.Action About;
    
    private Gtk.Action Quit;
    
    private Gtk.Action Preferences;
    
    private Gtk.Action @new;
    
    private Gtk.Action open;
    
    private Gtk.Action startTorrentButton;
    
    private Gtk.Action stopTorrentButton;
    
    private Gtk.Action removeTorrentButton;
    
    private Gtk.Action preferences;
    
    private Gtk.Action deleteTorrentButton;
    
    private Gtk.Action Columns;
    
    private Gtk.VBox vbox1;
    
    private Gtk.MenuBar menubar1;
    
    private Gtk.Toolbar toolbar1;
    
    private Gtk.HPaned hPaned;
    
    private Gtk.ScrolledWindow labelViewScrolledWindow;
    
    private Gtk.VPaned vPaned;
    
    private Gtk.ScrolledWindow torrentViewScrolledWindow;
    
    private Gtk.Notebook notebook1;
    
    private Gtk.ScrolledWindow scrolledwindow1;
    
    private Gtk.VBox vbox4;
    
    private Gtk.HBox hbox3;
    
    private Gtk.Label downloadProgressBarLabel;
    
    private Gtk.ProgressBar downloadedProgressBar;
    
    private Gtk.HBox hbox1;
    
    private Gtk.Frame frame1;
    
    private Gtk.Alignment GtkAlignment;
    
    private Gtk.VBox vbox2;
    
    private Gtk.HBox hbox12;
    
    private Gtk.Label elapsedTimeLabel;
    
    private Gtk.Label elapsedTimeValueLabel;
    
    private Gtk.HBox hbox2;
    
    private Gtk.Label label3;
    
    private Gtk.Label downloadedValueLabel;
    
    private Gtk.HBox hbox5;
    
    private Gtk.Label label5;
    
    private Gtk.Label uploadedValueLabel;
    
    private Gtk.Label GtkLabel6;
    
    private Gtk.Frame frame2;
    
    private Gtk.Alignment GtkAlignment1;
    
    private Gtk.VBox vbox3;
    
    private Gtk.HBox hbox6;
    
    private Gtk.Label label8;
    
    private Gtk.Label trackerUrlValueLabel;
    
    private Gtk.HBox hbox7;
    
    private Gtk.Label label2;
    
    private Gtk.Label trackerStatusValueLabel;
    
    private Gtk.HBox hbox8;
    
    private Gtk.Label label4;
    
    private Gtk.Label updateInValueLabel;
    
    private Gtk.Label GtkLabel7;
    
    private Gtk.Frame frame3;
    
    private Gtk.Alignment GtkAlignment2;
    
    private Gtk.VBox vbox5;
    
    private Gtk.HBox hbox4;
    
    private Gtk.Label label7;
    
    private Gtk.Label savePathValueLabel;
    
    private Gtk.HBox hbox9;
    
    private Gtk.Label label10;
    
    private Gtk.Label sizeValueLabel;
    
    private Gtk.HBox hbox11;
    
    private Gtk.Label label11;
    
    private Gtk.Label createdOnValueLabel;
    
    private Gtk.HBox hbox10;
    
    private Gtk.Label label12;
    
    private Gtk.Label commentValueLabel;
    
    private Gtk.Label GtkLabel8;
    
    private Gtk.Label label1;
    
    private Gtk.ScrolledWindow filesScrolledWindow;
    
    private Gtk.Label label9;
    
    private Gtk.ScrolledWindow peersScrolledWindow;
    
    private Gtk.Label label6;
    
    private Gtk.ScrolledWindow scrolledwindow2;
    
    private Gtk.HBox hbox13;
    
    private Gtk.Frame frame4;
    
    private Gtk.Alignment GtkAlignment3;
    
    private Gtk.ScrolledWindow selectLabelScrolledWindow;
    
    private Gtk.Label GtkLabel9;
    
    private Gtk.VBox vbox6;
    
    private Gtk.Frame frame5;
    
    private Gtk.Alignment GtkAlignment4;
    
    private Gtk.VBox vbox7;
    
    private Gtk.HBox hbox14;
    
    private Gtk.Label label14;
    
    private Gtk.SpinButton torrentUploadRateSpinButton;
    
    private Gtk.HBox hbox15;
    
    private Gtk.Label label15;
    
    private Gtk.SpinButton torrentDownloadRateSpinButton;
    
    private Gtk.HBox hbox16;
    
    private Gtk.Label label16;
    
    private Gtk.SpinButton torrentMaxConnectionsSpinButton;
    
    private Gtk.HBox hbox17;
    
    private Gtk.Label label17;
    
    private Gtk.SpinButton torrentUploadSlotSpinButton;
    
    private Gtk.Label GtkLabel10;
    
    private Gtk.HBox hbox18;
    
    private Gtk.Button saveTorrentSettingsButton;
    
    private Gtk.Label label13;
    
    private Gtk.Statusbar statusbar2;
    
    private Gtk.Label statusDownloadLabel;
    
    private Gtk.Label statusUploadLabel;
    
    protected virtual void Build() {
        Stetic.Gui.Initialize();
        // Widget MainWindow
        Gtk.UIManager w1 = new Gtk.UIManager();
        Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
        this.File = new Gtk.Action("File", Mono.Unix.Catalog.GetString("File"), null, null);
        this.File.ShortLabel = Mono.Unix.Catalog.GetString("File");
        w2.Add(this.File, null);
        this.Edit = new Gtk.Action("Edit", Mono.Unix.Catalog.GetString("Edit"), null, null);
        this.Edit.ShortLabel = Mono.Unix.Catalog.GetString("Edit");
        w2.Add(this.Edit, null);
        this.View = new Gtk.Action("View", Mono.Unix.Catalog.GetString("View"), null, null);
        this.View.ShortLabel = Mono.Unix.Catalog.GetString("View");
        w2.Add(this.View, null);
        this.Help = new Gtk.Action("Help", Mono.Unix.Catalog.GetString("Help"), null, null);
        this.Help.ShortLabel = Mono.Unix.Catalog.GetString("Help");
        w2.Add(this.Help, null);
        this.About = new Gtk.Action("About", Mono.Unix.Catalog.GetString("_About"), null, "gtk-about");
        this.About.ShortLabel = Mono.Unix.Catalog.GetString("_About");
        w2.Add(this.About, null);
        this.Quit = new Gtk.Action("Quit", Mono.Unix.Catalog.GetString("Quit"), null, "gtk-quit");
        this.Quit.ShortLabel = Mono.Unix.Catalog.GetString("Quit");
        w2.Add(this.Quit, null);
        this.Preferences = new Gtk.Action("Preferences", Mono.Unix.Catalog.GetString("_Preferences"), null, "gtk-preferences");
        this.Preferences.ShortLabel = Mono.Unix.Catalog.GetString("_Preferences");
        w2.Add(this.Preferences, null);
        this.@new = new Gtk.Action("new", null, null, "gtk-new");
        w2.Add(this.@new, null);
        this.open = new Gtk.Action("open", null, null, "gtk-open");
        w2.Add(this.open, null);
        this.startTorrentButton = new Gtk.Action("startTorrentButton", null, null, "gtk-media-play");
        this.startTorrentButton.Sensitive = false;
        w2.Add(this.startTorrentButton, null);
        this.stopTorrentButton = new Gtk.Action("stopTorrentButton", null, null, "gtk-media-stop");
        this.stopTorrentButton.Sensitive = false;
        w2.Add(this.stopTorrentButton, null);
        this.removeTorrentButton = new Gtk.Action("removeTorrentButton", null, null, "gtk-remove");
        this.removeTorrentButton.Sensitive = false;
        w2.Add(this.removeTorrentButton, null);
        this.preferences = new Gtk.Action("preferences", null, null, "gtk-preferences");
        w2.Add(this.preferences, null);
        this.deleteTorrentButton = new Gtk.Action("deleteTorrentButton", null, null, "gtk-delete");
        this.deleteTorrentButton.Sensitive = false;
        w2.Add(this.deleteTorrentButton, null);
        this.Columns = new Gtk.Action("Columns", Mono.Unix.Catalog.GetString("Columns"), null, null);
        this.Columns.ShortLabel = Mono.Unix.Catalog.GetString("Columns");
        w2.Add(this.Columns, null);
        w1.InsertActionGroup(w2, 0);
        this.AddAccelGroup(w1.AccelGroup);
        this.Name = "MainWindow";
        this.Title = Mono.Unix.Catalog.GetString("MonoTorrent");
        // Container child MainWindow.Gtk.Container+ContainerChild
        this.vbox1 = new Gtk.VBox();
        this.vbox1.Name = "vbox1";
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='File'><menuitem action='Quit'/></menu><menu action='Edit'><menuitem action='Preferences'/></menu><menu action='View'><menuitem action='Columns'/></menu><menu action='Help'><menuitem action='About'/></menu></menubar></ui>");
        this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
        this.menubar1.Name = "menubar1";
        this.vbox1.Add(this.menubar1);
        Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
        w3.Position = 0;
        w3.Expand = false;
        w3.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='new'/><toolitem action='open'/><separator/><toolitem action='startTorrentButton'/><toolitem action='stopTorrentButton'/><toolitem action='removeTorrentButton'/><toolitem action='deleteTorrentButton'/><separator/><toolitem action='preferences'/></toolbar></ui>");
        this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
        this.toolbar1.Name = "toolbar1";
        this.toolbar1.ShowArrow = false;
        this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
        this.vbox1.Add(this.toolbar1);
        Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
        w4.Position = 1;
        w4.Expand = false;
        w4.Fill = false;
        // Container child vbox1.Gtk.Box+BoxChild
        this.hPaned = new Gtk.HPaned();
        this.hPaned.CanFocus = true;
        this.hPaned.Name = "hPaned";
        this.hPaned.Position = 145;
        // Container child hPaned.Gtk.Paned+PanedChild
        this.labelViewScrolledWindow = new Gtk.ScrolledWindow();
        this.labelViewScrolledWindow.CanFocus = true;
        this.labelViewScrolledWindow.Name = "labelViewScrolledWindow";
        this.labelViewScrolledWindow.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.labelViewScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.hPaned.Add(this.labelViewScrolledWindow);
        Gtk.Paned.PanedChild w5 = ((Gtk.Paned.PanedChild)(this.hPaned[this.labelViewScrolledWindow]));
        w5.Resize = false;
        // Container child hPaned.Gtk.Paned+PanedChild
        this.vPaned = new Gtk.VPaned();
        this.vPaned.CanFocus = true;
        this.vPaned.Name = "vPaned";
        this.vPaned.Position = 160;
        // Container child vPaned.Gtk.Paned+PanedChild
        this.torrentViewScrolledWindow = new Gtk.ScrolledWindow();
        this.torrentViewScrolledWindow.CanFocus = true;
        this.torrentViewScrolledWindow.Name = "torrentViewScrolledWindow";
        this.torrentViewScrolledWindow.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.torrentViewScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.vPaned.Add(this.torrentViewScrolledWindow);
        Gtk.Paned.PanedChild w6 = ((Gtk.Paned.PanedChild)(this.vPaned[this.torrentViewScrolledWindow]));
        w6.Resize = false;
        // Container child vPaned.Gtk.Paned+PanedChild
        this.notebook1 = new Gtk.Notebook();
        this.notebook1.CanFocus = true;
        this.notebook1.Name = "notebook1";
        this.notebook1.CurrentPage = 3;
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.scrolledwindow1 = new Gtk.ScrolledWindow();
        this.scrolledwindow1.CanFocus = true;
        this.scrolledwindow1.Name = "scrolledwindow1";
        this.scrolledwindow1.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow1.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
        // Container child scrolledwindow1.Gtk.Container+ContainerChild
        Gtk.Viewport w7 = new Gtk.Viewport();
        w7.Name = "GtkViewport2";
        w7.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport2.Gtk.Container+ContainerChild
        this.vbox4 = new Gtk.VBox();
        this.vbox4.Name = "vbox4";
        this.vbox4.Spacing = 6;
        this.vbox4.BorderWidth = ((uint)(5));
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox3 = new Gtk.HBox();
        this.hbox3.Name = "hbox3";
        this.hbox3.Spacing = 6;
        // Container child hbox3.Gtk.Box+BoxChild
        this.downloadProgressBarLabel = new Gtk.Label();
        this.downloadProgressBarLabel.Name = "downloadProgressBarLabel";
        this.downloadProgressBarLabel.LabelProp = Mono.Unix.Catalog.GetString("Downloaded: ");
        this.hbox3.Add(this.downloadProgressBarLabel);
        Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.downloadProgressBarLabel]));
        w8.Position = 0;
        w8.Expand = false;
        w8.Fill = false;
        // Container child hbox3.Gtk.Box+BoxChild
        this.downloadedProgressBar = new Gtk.ProgressBar();
        this.downloadedProgressBar.Name = "downloadedProgressBar";
        this.hbox3.Add(this.downloadedProgressBar);
        Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.downloadedProgressBar]));
        w9.Position = 1;
        this.vbox4.Add(this.hbox3);
        Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
        w10.Position = 0;
        w10.Expand = false;
        w10.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.hbox1 = new Gtk.HBox();
        this.hbox1.Name = "hbox1";
        this.hbox1.Spacing = 6;
        // Container child hbox1.Gtk.Box+BoxChild
        this.frame1 = new Gtk.Frame();
        this.frame1.Name = "frame1";
        this.frame1.ShadowType = ((Gtk.ShadowType)(0));
        this.frame1.LabelXalign = 0F;
        // Container child frame1.Gtk.Container+ContainerChild
        this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment.Name = "GtkAlignment";
        this.GtkAlignment.LeftPadding = ((uint)(12));
        // Container child GtkAlignment.Gtk.Container+ContainerChild
        this.vbox2 = new Gtk.VBox();
        this.vbox2.Name = "vbox2";
        this.vbox2.Spacing = 6;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox12 = new Gtk.HBox();
        this.hbox12.Name = "hbox12";
        this.hbox12.Spacing = 6;
        // Container child hbox12.Gtk.Box+BoxChild
        this.elapsedTimeLabel = new Gtk.Label();
        this.elapsedTimeLabel.Name = "elapsedTimeLabel";
        this.elapsedTimeLabel.LabelProp = Mono.Unix.Catalog.GetString("Elapsed Time:");
        this.hbox12.Add(this.elapsedTimeLabel);
        Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox12[this.elapsedTimeLabel]));
        w11.Position = 0;
        w11.Expand = false;
        w11.Fill = false;
        // Container child hbox12.Gtk.Box+BoxChild
        this.elapsedTimeValueLabel = new Gtk.Label();
        this.elapsedTimeValueLabel.Name = "elapsedTimeValueLabel";
        this.elapsedTimeValueLabel.LabelProp = "";
        this.hbox12.Add(this.elapsedTimeValueLabel);
        Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox12[this.elapsedTimeValueLabel]));
        w12.Position = 1;
        w12.Expand = false;
        w12.Fill = false;
        this.vbox2.Add(this.hbox12);
        Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox12]));
        w13.Position = 0;
        w13.Expand = false;
        w13.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox2 = new Gtk.HBox();
        this.hbox2.Name = "hbox2";
        this.hbox2.Spacing = 6;
        // Container child hbox2.Gtk.Box+BoxChild
        this.label3 = new Gtk.Label();
        this.label3.Name = "label3";
        this.label3.LabelProp = Mono.Unix.Catalog.GetString("Downloaded:");
        this.hbox2.Add(this.label3);
        Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox2[this.label3]));
        w14.Position = 0;
        w14.Expand = false;
        w14.Fill = false;
        // Container child hbox2.Gtk.Box+BoxChild
        this.downloadedValueLabel = new Gtk.Label();
        this.downloadedValueLabel.Name = "downloadedValueLabel";
        this.downloadedValueLabel.LabelProp = "";
        this.hbox2.Add(this.downloadedValueLabel);
        Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox2[this.downloadedValueLabel]));
        w15.Position = 1;
        w15.Expand = false;
        w15.Fill = false;
        this.vbox2.Add(this.hbox2);
        Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
        w16.Position = 1;
        w16.Expand = false;
        w16.Fill = false;
        // Container child vbox2.Gtk.Box+BoxChild
        this.hbox5 = new Gtk.HBox();
        this.hbox5.Name = "hbox5";
        this.hbox5.Spacing = 6;
        // Container child hbox5.Gtk.Box+BoxChild
        this.label5 = new Gtk.Label();
        this.label5.Name = "label5";
        this.label5.LabelProp = Mono.Unix.Catalog.GetString("Uploaded:");
        this.hbox5.Add(this.label5);
        Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox5[this.label5]));
        w17.Position = 0;
        w17.Expand = false;
        w17.Fill = false;
        // Container child hbox5.Gtk.Box+BoxChild
        this.uploadedValueLabel = new Gtk.Label();
        this.uploadedValueLabel.Name = "uploadedValueLabel";
        this.uploadedValueLabel.LabelProp = "";
        this.hbox5.Add(this.uploadedValueLabel);
        Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox5[this.uploadedValueLabel]));
        w18.Position = 1;
        w18.Expand = false;
        w18.Fill = false;
        this.vbox2.Add(this.hbox5);
        Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
        w19.Position = 2;
        w19.Expand = false;
        w19.Fill = false;
        this.GtkAlignment.Add(this.vbox2);
        this.frame1.Add(this.GtkAlignment);
        this.GtkLabel6 = new Gtk.Label();
        this.GtkLabel6.Name = "GtkLabel6";
        this.GtkLabel6.LabelProp = Mono.Unix.Catalog.GetString("<b>Transfer</b>");
        this.GtkLabel6.UseMarkup = true;
        this.frame1.LabelWidget = this.GtkLabel6;
        this.hbox1.Add(this.frame1);
        Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame1]));
        w22.Position = 0;
        w22.Expand = false;
        w22.Fill = false;
        // Container child hbox1.Gtk.Box+BoxChild
        this.frame2 = new Gtk.Frame();
        this.frame2.Name = "frame2";
        this.frame2.ShadowType = ((Gtk.ShadowType)(0));
        this.frame2.LabelXalign = 0F;
        // Container child frame2.Gtk.Container+ContainerChild
        this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment1.Name = "GtkAlignment1";
        this.GtkAlignment1.LeftPadding = ((uint)(12));
        // Container child GtkAlignment1.Gtk.Container+ContainerChild
        this.vbox3 = new Gtk.VBox();
        this.vbox3.Name = "vbox3";
        this.vbox3.Spacing = 6;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox6 = new Gtk.HBox();
        this.hbox6.Name = "hbox6";
        this.hbox6.Spacing = 6;
        // Container child hbox6.Gtk.Box+BoxChild
        this.label8 = new Gtk.Label();
        this.label8.Name = "label8";
        this.label8.LabelProp = Mono.Unix.Catalog.GetString("URL:");
        this.hbox6.Add(this.label8);
        Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox6[this.label8]));
        w23.Position = 0;
        w23.Expand = false;
        w23.Fill = false;
        // Container child hbox6.Gtk.Box+BoxChild
        this.trackerUrlValueLabel = new Gtk.Label();
        this.trackerUrlValueLabel.Name = "trackerUrlValueLabel";
        this.trackerUrlValueLabel.LabelProp = "";
        this.hbox6.Add(this.trackerUrlValueLabel);
        Gtk.Box.BoxChild w24 = ((Gtk.Box.BoxChild)(this.hbox6[this.trackerUrlValueLabel]));
        w24.Position = 1;
        w24.Expand = false;
        w24.Fill = false;
        this.vbox3.Add(this.hbox6);
        Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox6]));
        w25.Position = 0;
        w25.Expand = false;
        w25.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox7 = new Gtk.HBox();
        this.hbox7.Name = "hbox7";
        this.hbox7.Spacing = 6;
        // Container child hbox7.Gtk.Box+BoxChild
        this.label2 = new Gtk.Label();
        this.label2.Name = "label2";
        this.label2.LabelProp = Mono.Unix.Catalog.GetString("Status:");
        this.hbox7.Add(this.label2);
        Gtk.Box.BoxChild w26 = ((Gtk.Box.BoxChild)(this.hbox7[this.label2]));
        w26.Position = 0;
        w26.Expand = false;
        w26.Fill = false;
        // Container child hbox7.Gtk.Box+BoxChild
        this.trackerStatusValueLabel = new Gtk.Label();
        this.trackerStatusValueLabel.Name = "trackerStatusValueLabel";
        this.trackerStatusValueLabel.LabelProp = "";
        this.hbox7.Add(this.trackerStatusValueLabel);
        Gtk.Box.BoxChild w27 = ((Gtk.Box.BoxChild)(this.hbox7[this.trackerStatusValueLabel]));
        w27.Position = 1;
        w27.Expand = false;
        w27.Fill = false;
        this.vbox3.Add(this.hbox7);
        Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox7]));
        w28.Position = 1;
        w28.Expand = false;
        w28.Fill = false;
        // Container child vbox3.Gtk.Box+BoxChild
        this.hbox8 = new Gtk.HBox();
        this.hbox8.Name = "hbox8";
        this.hbox8.Spacing = 6;
        // Container child hbox8.Gtk.Box+BoxChild
        this.label4 = new Gtk.Label();
        this.label4.Name = "label4";
        this.label4.LabelProp = Mono.Unix.Catalog.GetString("Last updated:");
        this.hbox8.Add(this.label4);
        Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.hbox8[this.label4]));
        w29.Position = 0;
        w29.Expand = false;
        w29.Fill = false;
        // Container child hbox8.Gtk.Box+BoxChild
        this.updateInValueLabel = new Gtk.Label();
        this.updateInValueLabel.Name = "updateInValueLabel";
        this.updateInValueLabel.LabelProp = "";
        this.hbox8.Add(this.updateInValueLabel);
        Gtk.Box.BoxChild w30 = ((Gtk.Box.BoxChild)(this.hbox8[this.updateInValueLabel]));
        w30.Position = 1;
        w30.Expand = false;
        w30.Fill = false;
        this.vbox3.Add(this.hbox8);
        Gtk.Box.BoxChild w31 = ((Gtk.Box.BoxChild)(this.vbox3[this.hbox8]));
        w31.Position = 2;
        w31.Expand = false;
        w31.Fill = false;
        this.GtkAlignment1.Add(this.vbox3);
        this.frame2.Add(this.GtkAlignment1);
        this.GtkLabel7 = new Gtk.Label();
        this.GtkLabel7.Name = "GtkLabel7";
        this.GtkLabel7.LabelProp = Mono.Unix.Catalog.GetString("<b>Tracker</b>");
        this.GtkLabel7.UseMarkup = true;
        this.frame2.LabelWidget = this.GtkLabel7;
        this.hbox1.Add(this.frame2);
        Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame2]));
        w34.Position = 1;
        w34.Expand = false;
        w34.Fill = false;
        this.vbox4.Add(this.hbox1);
        Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
        w35.Position = 1;
        w35.Expand = false;
        w35.Fill = false;
        // Container child vbox4.Gtk.Box+BoxChild
        this.frame3 = new Gtk.Frame();
        this.frame3.Name = "frame3";
        this.frame3.ShadowType = ((Gtk.ShadowType)(0));
        this.frame3.LabelXalign = 0F;
        // Container child frame3.Gtk.Container+ContainerChild
        this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment2.Name = "GtkAlignment2";
        this.GtkAlignment2.LeftPadding = ((uint)(12));
        // Container child GtkAlignment2.Gtk.Container+ContainerChild
        this.vbox5 = new Gtk.VBox();
        this.vbox5.Name = "vbox5";
        this.vbox5.Spacing = 6;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox4 = new Gtk.HBox();
        this.hbox4.Name = "hbox4";
        this.hbox4.Spacing = 6;
        // Container child hbox4.Gtk.Box+BoxChild
        this.label7 = new Gtk.Label();
        this.label7.Name = "label7";
        this.label7.LabelProp = Mono.Unix.Catalog.GetString("Save path:");
        this.hbox4.Add(this.label7);
        Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.hbox4[this.label7]));
        w36.Position = 0;
        w36.Expand = false;
        w36.Fill = false;
        // Container child hbox4.Gtk.Box+BoxChild
        this.savePathValueLabel = new Gtk.Label();
        this.savePathValueLabel.Name = "savePathValueLabel";
        this.savePathValueLabel.LabelProp = "";
        this.hbox4.Add(this.savePathValueLabel);
        Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.hbox4[this.savePathValueLabel]));
        w37.Position = 1;
        w37.Expand = false;
        w37.Fill = false;
        this.vbox5.Add(this.hbox4);
        Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
        w38.Position = 0;
        w38.Expand = false;
        w38.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox9 = new Gtk.HBox();
        this.hbox9.Name = "hbox9";
        this.hbox9.Spacing = 6;
        // Container child hbox9.Gtk.Box+BoxChild
        this.label10 = new Gtk.Label();
        this.label10.Name = "label10";
        this.label10.LabelProp = Mono.Unix.Catalog.GetString("Size:");
        this.hbox9.Add(this.label10);
        Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.hbox9[this.label10]));
        w39.Position = 0;
        w39.Expand = false;
        w39.Fill = false;
        // Container child hbox9.Gtk.Box+BoxChild
        this.sizeValueLabel = new Gtk.Label();
        this.sizeValueLabel.Name = "sizeValueLabel";
        this.sizeValueLabel.LabelProp = "";
        this.hbox9.Add(this.sizeValueLabel);
        Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.hbox9[this.sizeValueLabel]));
        w40.Position = 1;
        w40.Expand = false;
        w40.Fill = false;
        this.vbox5.Add(this.hbox9);
        Gtk.Box.BoxChild w41 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox9]));
        w41.Position = 1;
        w41.Expand = false;
        w41.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox11 = new Gtk.HBox();
        this.hbox11.Name = "hbox11";
        this.hbox11.Spacing = 6;
        // Container child hbox11.Gtk.Box+BoxChild
        this.label11 = new Gtk.Label();
        this.label11.Name = "label11";
        this.label11.LabelProp = Mono.Unix.Catalog.GetString("Created on:");
        this.hbox11.Add(this.label11);
        Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.hbox11[this.label11]));
        w42.Position = 0;
        w42.Expand = false;
        w42.Fill = false;
        // Container child hbox11.Gtk.Box+BoxChild
        this.createdOnValueLabel = new Gtk.Label();
        this.createdOnValueLabel.Name = "createdOnValueLabel";
        this.createdOnValueLabel.LabelProp = "";
        this.hbox11.Add(this.createdOnValueLabel);
        Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.hbox11[this.createdOnValueLabel]));
        w43.Position = 1;
        w43.Expand = false;
        w43.Fill = false;
        this.vbox5.Add(this.hbox11);
        Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox11]));
        w44.Position = 2;
        w44.Expand = false;
        w44.Fill = false;
        // Container child vbox5.Gtk.Box+BoxChild
        this.hbox10 = new Gtk.HBox();
        this.hbox10.Name = "hbox10";
        this.hbox10.Spacing = 6;
        // Container child hbox10.Gtk.Box+BoxChild
        this.label12 = new Gtk.Label();
        this.label12.Name = "label12";
        this.label12.LabelProp = Mono.Unix.Catalog.GetString("Comment:");
        this.hbox10.Add(this.label12);
        Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.hbox10[this.label12]));
        w45.Position = 0;
        w45.Expand = false;
        w45.Fill = false;
        // Container child hbox10.Gtk.Box+BoxChild
        this.commentValueLabel = new Gtk.Label();
        this.commentValueLabel.Name = "commentValueLabel";
        this.commentValueLabel.LabelProp = "";
        this.hbox10.Add(this.commentValueLabel);
        Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.hbox10[this.commentValueLabel]));
        w46.Position = 2;
        w46.Expand = false;
        w46.Fill = false;
        this.vbox5.Add(this.hbox10);
        Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.vbox5[this.hbox10]));
        w47.Position = 3;
        w47.Expand = false;
        w47.Fill = false;
        this.GtkAlignment2.Add(this.vbox5);
        this.frame3.Add(this.GtkAlignment2);
        this.GtkLabel8 = new Gtk.Label();
        this.GtkLabel8.Name = "GtkLabel8";
        this.GtkLabel8.LabelProp = Mono.Unix.Catalog.GetString("<b>General</b>");
        this.GtkLabel8.UseMarkup = true;
        this.frame3.LabelWidget = this.GtkLabel8;
        this.vbox4.Add(this.frame3);
        Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.vbox4[this.frame3]));
        w50.Position = 2;
        w50.Expand = false;
        w50.Fill = false;
        w7.Add(this.vbox4);
        this.scrolledwindow1.Add(w7);
        this.notebook1.Add(this.scrolledwindow1);
        Gtk.Notebook.NotebookChild w53 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.scrolledwindow1]));
        w53.TabExpand = false;
        // Notebook tab
        this.label1 = new Gtk.Label();
        this.label1.Name = "label1";
        this.label1.LabelProp = Mono.Unix.Catalog.GetString("General");
        this.notebook1.SetTabLabel(this.scrolledwindow1, this.label1);
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.filesScrolledWindow = new Gtk.ScrolledWindow();
        this.filesScrolledWindow.CanFocus = true;
        this.filesScrolledWindow.Name = "filesScrolledWindow";
        this.filesScrolledWindow.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.filesScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.filesScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        this.notebook1.Add(this.filesScrolledWindow);
        Gtk.Notebook.NotebookChild w54 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.filesScrolledWindow]));
        w54.Position = 1;
        w54.TabExpand = false;
        // Notebook tab
        this.label9 = new Gtk.Label();
        this.label9.Name = "label9";
        this.label9.LabelProp = Mono.Unix.Catalog.GetString("Files");
        this.notebook1.SetTabLabel(this.filesScrolledWindow, this.label9);
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.peersScrolledWindow = new Gtk.ScrolledWindow();
        this.peersScrolledWindow.CanFocus = true;
        this.peersScrolledWindow.Name = "peersScrolledWindow";
        this.peersScrolledWindow.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.peersScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.peersScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        this.notebook1.Add(this.peersScrolledWindow);
        Gtk.Notebook.NotebookChild w55 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.peersScrolledWindow]));
        w55.Position = 2;
        w55.TabExpand = false;
        // Notebook tab
        this.label6 = new Gtk.Label();
        this.label6.Name = "label6";
        this.label6.LabelProp = Mono.Unix.Catalog.GetString("Peers");
        this.notebook1.SetTabLabel(this.peersScrolledWindow, this.label6);
        // Container child notebook1.Gtk.Notebook+NotebookChild
        this.scrolledwindow2 = new Gtk.ScrolledWindow();
        this.scrolledwindow2.CanFocus = true;
        this.scrolledwindow2.Name = "scrolledwindow2";
        this.scrolledwindow2.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow2.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
        // Container child scrolledwindow2.Gtk.Container+ContainerChild
        Gtk.Viewport w56 = new Gtk.Viewport();
        w56.Name = "GtkViewport5";
        w56.ShadowType = ((Gtk.ShadowType)(0));
        // Container child GtkViewport5.Gtk.Container+ContainerChild
        this.hbox13 = new Gtk.HBox();
        this.hbox13.Name = "hbox13";
        this.hbox13.Spacing = 6;
        // Container child hbox13.Gtk.Box+BoxChild
        this.frame4 = new Gtk.Frame();
        this.frame4.Name = "frame4";
        this.frame4.ShadowType = ((Gtk.ShadowType)(0));
        this.frame4.LabelXalign = 0F;
        // Container child frame4.Gtk.Container+ContainerChild
        this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment3.WidthRequest = 250;
        this.GtkAlignment3.Name = "GtkAlignment3";
        this.GtkAlignment3.LeftPadding = ((uint)(12));
        // Container child GtkAlignment3.Gtk.Container+ContainerChild
        this.selectLabelScrolledWindow = new Gtk.ScrolledWindow();
        this.selectLabelScrolledWindow.CanFocus = true;
        this.selectLabelScrolledWindow.Name = "selectLabelScrolledWindow";
        this.selectLabelScrolledWindow.VscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.selectLabelScrolledWindow.HscrollbarPolicy = ((Gtk.PolicyType)(1));
        this.selectLabelScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
        this.GtkAlignment3.Add(this.selectLabelScrolledWindow);
        this.frame4.Add(this.GtkAlignment3);
        this.GtkLabel9 = new Gtk.Label();
        this.GtkLabel9.Name = "GtkLabel9";
        this.GtkLabel9.LabelProp = Mono.Unix.Catalog.GetString("<b>Set labels</b>");
        this.GtkLabel9.UseMarkup = true;
        this.frame4.LabelWidget = this.GtkLabel9;
        this.hbox13.Add(this.frame4);
        Gtk.Box.BoxChild w59 = ((Gtk.Box.BoxChild)(this.hbox13[this.frame4]));
        w59.Position = 0;
        w59.Expand = false;
        w59.Fill = false;
        // Container child hbox13.Gtk.Box+BoxChild
        this.vbox6 = new Gtk.VBox();
        this.vbox6.Name = "vbox6";
        this.vbox6.Spacing = 6;
        // Container child vbox6.Gtk.Box+BoxChild
        this.frame5 = new Gtk.Frame();
        this.frame5.Name = "frame5";
        this.frame5.ShadowType = ((Gtk.ShadowType)(0));
        this.frame5.LabelXalign = 0F;
        // Container child frame5.Gtk.Container+ContainerChild
        this.GtkAlignment4 = new Gtk.Alignment(0F, 0F, 1F, 1F);
        this.GtkAlignment4.Name = "GtkAlignment4";
        this.GtkAlignment4.LeftPadding = ((uint)(12));
        // Container child GtkAlignment4.Gtk.Container+ContainerChild
        this.vbox7 = new Gtk.VBox();
        this.vbox7.Name = "vbox7";
        this.vbox7.Spacing = 6;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox14 = new Gtk.HBox();
        this.hbox14.Name = "hbox14";
        this.hbox14.Spacing = 6;
        // Container child hbox14.Gtk.Box+BoxChild
        this.label14 = new Gtk.Label();
        this.label14.Name = "label14";
        this.label14.LabelProp = Mono.Unix.Catalog.GetString("Maximum upload rate:");
        this.hbox14.Add(this.label14);
        Gtk.Box.BoxChild w60 = ((Gtk.Box.BoxChild)(this.hbox14[this.label14]));
        w60.Position = 0;
        w60.Expand = false;
        w60.Fill = false;
        // Container child hbox14.Gtk.Box+BoxChild
        this.torrentUploadRateSpinButton = new Gtk.SpinButton(0, 100, 1);
        this.torrentUploadRateSpinButton.CanFocus = true;
        this.torrentUploadRateSpinButton.Name = "torrentUploadRateSpinButton";
        this.torrentUploadRateSpinButton.Adjustment.PageIncrement = 10;
        this.torrentUploadRateSpinButton.ClimbRate = 1;
        this.torrentUploadRateSpinButton.Numeric = true;
        this.hbox14.Add(this.torrentUploadRateSpinButton);
        Gtk.Box.BoxChild w61 = ((Gtk.Box.BoxChild)(this.hbox14[this.torrentUploadRateSpinButton]));
        w61.Position = 1;
        w61.Expand = false;
        w61.Fill = false;
        this.vbox7.Add(this.hbox14);
        Gtk.Box.BoxChild w62 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox14]));
        w62.Position = 0;
        w62.Expand = false;
        w62.Fill = false;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox15 = new Gtk.HBox();
        this.hbox15.Name = "hbox15";
        this.hbox15.Spacing = 6;
        // Container child hbox15.Gtk.Box+BoxChild
        this.label15 = new Gtk.Label();
        this.label15.Name = "label15";
        this.label15.LabelProp = Mono.Unix.Catalog.GetString("Maximum download rate:");
        this.hbox15.Add(this.label15);
        Gtk.Box.BoxChild w63 = ((Gtk.Box.BoxChild)(this.hbox15[this.label15]));
        w63.Position = 0;
        w63.Expand = false;
        w63.Fill = false;
        // Container child hbox15.Gtk.Box+BoxChild
        this.torrentDownloadRateSpinButton = new Gtk.SpinButton(0, 100, 1);
        this.torrentDownloadRateSpinButton.CanFocus = true;
        this.torrentDownloadRateSpinButton.Name = "torrentDownloadRateSpinButton";
        this.torrentDownloadRateSpinButton.Adjustment.PageIncrement = 10;
        this.torrentDownloadRateSpinButton.ClimbRate = 1;
        this.torrentDownloadRateSpinButton.Numeric = true;
        this.hbox15.Add(this.torrentDownloadRateSpinButton);
        Gtk.Box.BoxChild w64 = ((Gtk.Box.BoxChild)(this.hbox15[this.torrentDownloadRateSpinButton]));
        w64.Position = 1;
        w64.Expand = false;
        w64.Fill = false;
        this.vbox7.Add(this.hbox15);
        Gtk.Box.BoxChild w65 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox15]));
        w65.Position = 1;
        w65.Expand = false;
        w65.Fill = false;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox16 = new Gtk.HBox();
        this.hbox16.Name = "hbox16";
        this.hbox16.Spacing = 6;
        // Container child hbox16.Gtk.Box+BoxChild
        this.label16 = new Gtk.Label();
        this.label16.Name = "label16";
        this.label16.LabelProp = Mono.Unix.Catalog.GetString("Maximum connections:");
        this.hbox16.Add(this.label16);
        Gtk.Box.BoxChild w66 = ((Gtk.Box.BoxChild)(this.hbox16[this.label16]));
        w66.Position = 0;
        w66.Expand = false;
        w66.Fill = false;
        // Container child hbox16.Gtk.Box+BoxChild
        this.torrentMaxConnectionsSpinButton = new Gtk.SpinButton(0, 100, 1);
        this.torrentMaxConnectionsSpinButton.CanFocus = true;
        this.torrentMaxConnectionsSpinButton.Name = "torrentMaxConnectionsSpinButton";
        this.torrentMaxConnectionsSpinButton.Adjustment.PageIncrement = 10;
        this.torrentMaxConnectionsSpinButton.ClimbRate = 1;
        this.torrentMaxConnectionsSpinButton.Numeric = true;
        this.hbox16.Add(this.torrentMaxConnectionsSpinButton);
        Gtk.Box.BoxChild w67 = ((Gtk.Box.BoxChild)(this.hbox16[this.torrentMaxConnectionsSpinButton]));
        w67.Position = 1;
        w67.Expand = false;
        w67.Fill = false;
        this.vbox7.Add(this.hbox16);
        Gtk.Box.BoxChild w68 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox16]));
        w68.Position = 2;
        w68.Expand = false;
        w68.Fill = false;
        // Container child vbox7.Gtk.Box+BoxChild
        this.hbox17 = new Gtk.HBox();
        this.hbox17.Name = "hbox17";
        this.hbox17.Spacing = 6;
        // Container child hbox17.Gtk.Box+BoxChild
        this.label17 = new Gtk.Label();
        this.label17.Name = "label17";
        this.label17.LabelProp = Mono.Unix.Catalog.GetString("Upload slots:");
        this.hbox17.Add(this.label17);
        Gtk.Box.BoxChild w69 = ((Gtk.Box.BoxChild)(this.hbox17[this.label17]));
        w69.Position = 0;
        w69.Expand = false;
        w69.Fill = false;
        // Container child hbox17.Gtk.Box+BoxChild
        this.torrentUploadSlotSpinButton = new Gtk.SpinButton(0, 100, 1);
        this.torrentUploadSlotSpinButton.CanFocus = true;
        this.torrentUploadSlotSpinButton.Name = "torrentUploadSlotSpinButton";
        this.torrentUploadSlotSpinButton.Adjustment.PageIncrement = 10;
        this.torrentUploadSlotSpinButton.ClimbRate = 1;
        this.torrentUploadSlotSpinButton.Numeric = true;
        this.hbox17.Add(this.torrentUploadSlotSpinButton);
        Gtk.Box.BoxChild w70 = ((Gtk.Box.BoxChild)(this.hbox17[this.torrentUploadSlotSpinButton]));
        w70.Position = 1;
        w70.Expand = false;
        w70.Fill = false;
        this.vbox7.Add(this.hbox17);
        Gtk.Box.BoxChild w71 = ((Gtk.Box.BoxChild)(this.vbox7[this.hbox17]));
        w71.Position = 3;
        w71.Expand = false;
        w71.Fill = false;
        this.GtkAlignment4.Add(this.vbox7);
        this.frame5.Add(this.GtkAlignment4);
        this.GtkLabel10 = new Gtk.Label();
        this.GtkLabel10.Name = "GtkLabel10";
        this.GtkLabel10.LabelProp = Mono.Unix.Catalog.GetString("<b>Bandwidth</b>");
        this.GtkLabel10.UseMarkup = true;
        this.frame5.LabelWidget = this.GtkLabel10;
        this.vbox6.Add(this.frame5);
        Gtk.Box.BoxChild w74 = ((Gtk.Box.BoxChild)(this.vbox6[this.frame5]));
        w74.Position = 0;
        w74.Expand = false;
        w74.Fill = false;
        // Container child vbox6.Gtk.Box+BoxChild
        this.hbox18 = new Gtk.HBox();
        this.hbox18.Name = "hbox18";
        this.hbox18.Spacing = 6;
        // Container child hbox18.Gtk.Box+BoxChild
        this.saveTorrentSettingsButton = new Gtk.Button();
        this.saveTorrentSettingsButton.CanFocus = true;
        this.saveTorrentSettingsButton.Name = "saveTorrentSettingsButton";
        this.saveTorrentSettingsButton.UseUnderline = true;
        this.saveTorrentSettingsButton.Label = Mono.Unix.Catalog.GetString("Save");
        this.hbox18.Add(this.saveTorrentSettingsButton);
        Gtk.Box.BoxChild w75 = ((Gtk.Box.BoxChild)(this.hbox18[this.saveTorrentSettingsButton]));
        w75.Position = 2;
        w75.Expand = false;
        w75.Fill = false;
        this.vbox6.Add(this.hbox18);
        Gtk.Box.BoxChild w76 = ((Gtk.Box.BoxChild)(this.vbox6[this.hbox18]));
        w76.Position = 1;
        w76.Expand = false;
        w76.Fill = false;
        this.hbox13.Add(this.vbox6);
        Gtk.Box.BoxChild w77 = ((Gtk.Box.BoxChild)(this.hbox13[this.vbox6]));
        w77.Position = 1;
        w77.Expand = false;
        w77.Fill = false;
        w56.Add(this.hbox13);
        this.scrolledwindow2.Add(w56);
        this.notebook1.Add(this.scrolledwindow2);
        Gtk.Notebook.NotebookChild w80 = ((Gtk.Notebook.NotebookChild)(this.notebook1[this.scrolledwindow2]));
        w80.Position = 3;
        w80.TabExpand = false;
        // Notebook tab
        this.label13 = new Gtk.Label();
        this.label13.Name = "label13";
        this.label13.LabelProp = Mono.Unix.Catalog.GetString("Options");
        this.notebook1.SetTabLabel(this.scrolledwindow2, this.label13);
        this.vPaned.Add(this.notebook1);
        this.hPaned.Add(this.vPaned);
        this.vbox1.Add(this.hPaned);
        Gtk.Box.BoxChild w83 = ((Gtk.Box.BoxChild)(this.vbox1[this.hPaned]));
        w83.Position = 2;
        // Container child vbox1.Gtk.Box+BoxChild
        this.statusbar2 = new Gtk.Statusbar();
        this.statusbar2.Name = "statusbar2";
        this.statusbar2.Spacing = 6;
        // Container child statusbar2.Gtk.Box+BoxChild
        this.statusDownloadLabel = new Gtk.Label();
        this.statusDownloadLabel.Name = "statusDownloadLabel";
        this.statusDownloadLabel.LabelProp = Mono.Unix.Catalog.GetString("<small>D: 0.00 kB</small>");
        this.statusDownloadLabel.UseMarkup = true;
        this.statusbar2.Add(this.statusDownloadLabel);
        Gtk.Box.BoxChild w84 = ((Gtk.Box.BoxChild)(this.statusbar2[this.statusDownloadLabel]));
        w84.Position = 1;
        w84.Expand = false;
        w84.Fill = false;
        // Container child statusbar2.Gtk.Box+BoxChild
        this.statusUploadLabel = new Gtk.Label();
        this.statusUploadLabel.Name = "statusUploadLabel";
        this.statusUploadLabel.LabelProp = Mono.Unix.Catalog.GetString("<small>U: 0.00 kB</small>");
        this.statusUploadLabel.UseMarkup = true;
        this.statusbar2.Add(this.statusUploadLabel);
        Gtk.Box.BoxChild w85 = ((Gtk.Box.BoxChild)(this.statusbar2[this.statusUploadLabel]));
        w85.Position = 2;
        w85.Expand = false;
        w85.Fill = false;
        this.vbox1.Add(this.statusbar2);
        Gtk.Box.BoxChild w86 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar2]));
        w86.Position = 3;
        w86.Expand = false;
        w86.Fill = false;
        this.Add(this.vbox1);
        if ((this.Child != null)) {
            this.Child.ShowAll();
        }
        this.DefaultWidth = 762;
        this.DefaultHeight = 559;
        this.Hide();
        this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        this.About.Activated += new System.EventHandler(this.OnAboutActivated);
        this.Quit.Activated += new System.EventHandler(this.OnQuitActivated);
        this.Preferences.Activated += new System.EventHandler(this.OnPreferencesActivated);
        this.@new.Activated += new System.EventHandler(this.OnNewActivated);
        this.open.Activated += new System.EventHandler(this.OnOpenActivated);
        this.startTorrentButton.Activated += new System.EventHandler(this.OnStartTorrentActivated);
        this.stopTorrentButton.Activated += new System.EventHandler(this.OnStopTorrentActivated);
        this.removeTorrentButton.Activated += new System.EventHandler(this.OnRemoveTorrentButtonActivated);
        this.preferences.Activated += new System.EventHandler(this.OnPreferencesActivated);
        this.deleteTorrentButton.Activated += new System.EventHandler(this.OnDeleteTorrentButtonActivated);
        this.Columns.Activated += new System.EventHandler(this.OnColumnsActivated);
        this.saveTorrentSettingsButton.Clicked += new System.EventHandler(this.OnSaveTorrentSettingsButtonClicked);
    }
}
