// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monsoon {
    
    
    public partial class MainWindow {
        
        private Gtk.Action FileAction;
        
        private Gtk.Action EditAction;
        
        private Gtk.Action ViewAction;
        
        private Gtk.Action HelpAction;
        
        private Gtk.Action About;
        
        private Gtk.Action Quit;
        
        private Gtk.Action stopTorrentButton;
        
        private Gtk.Action removeTorrentButton;
        
        private Gtk.Action preferences;
        
        private Gtk.Action deleteTorrentButton;
        
        private Gtk.Action EditColumns;
        
        private Gtk.ToggleAction ShowLabels;
        
        private Gtk.ToggleAction ShowDetailedInfo;
        
        private Gtk.Action OpenTorrent;
        
        private Gtk.Action startTorrentButton;
        
        private Gtk.Action NewTorrent;
        
        private Gtk.Action Plugins;
        
        private Gtk.Action ReportBugAction;
        
        private Gtk.VBox vbox1;
        
        private Gtk.MenuBar menubar1;
        
        private Gtk.Toolbar toolbar1;
        
        private Gtk.HPaned hPaned;
        
        private Gtk.ScrolledWindow labelViewScrolledWindow;
        
        private Gtk.VPaned vPaned;
        
        private Gtk.ScrolledWindow torrentViewScrolledWindow;
        
        private Gtk.Notebook detailNotebook;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.VBox vbox4;
        
        private Gtk.HBox hbox3;
        
        private Gtk.Label statusProgressBarLabel;
        
        private Gtk.ProgressBar statusProgressBar;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment;
        
        private Gtk.Table table8;
        
        private Gtk.Label downloadedValueLabel;
        
        private Gtk.Label elapsedTimeLabel;
        
        private Gtk.Label elapsedTimeValueLabel;
        
        private Gtk.Label hashFailsLabel;
        
        private Gtk.Label label21;
        
        private Gtk.Label label22;
        
        private Gtk.Label label3;
        
        private Gtk.Label label5;
        
        private Gtk.Label swarmSpeedLabel;
        
        private Gtk.Label uploadedValueLabel;
        
        private Gtk.Label GtkLabel6;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table7;
        
        private Gtk.Label label19;
        
        private Gtk.Label label20;
        
        private Gtk.Label label23;
        
        private Gtk.Label label4;
        
        private Gtk.Label label8;
        
        private Gtk.Label lastUpdatedLabel;
        
        private Gtk.Label messageLabel;
        
        private Gtk.Label trackerStatusValueLabel;
        
        private Gtk.Label trackerUrlValueLabel;
        
        private Gtk.Label updateInLabel;
        
        private Gtk.Label GtkLabel7;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.Table table9;
        
        private Gtk.Label commentValueLabel;
        
        private Gtk.Label createdOnValueLabel;
        
        private Gtk.Label label10;
        
        private Gtk.Label label11;
        
        private Gtk.Label label12;
        
        private Gtk.Label label7;
        
        private Gtk.Label savePathValueLabel;
        
        private Gtk.Label sizeValueLabel;
        
        private Gtk.Label GtkLabel8;
        
        private Gtk.Label label1;
        
        private Gtk.ScrolledWindow filesScrolledWindow;
        
        private Gtk.Label label9;
        
        private Gtk.ScrolledWindow piecesScrolledWindow;
        
        private Gtk.Label label18;
        
        private Gtk.ScrolledWindow peersScrolledWindow;
        
        private Gtk.Label label6;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.HBox hbox13;
        
        private Gtk.VBox vbox6;
        
        private Gtk.Frame frame5;
        
        private Gtk.Alignment GtkAlignment4;
        
        private Gtk.Table table2;
        
        private Gtk.Label label14;
        
        private Gtk.Label label15;
        
        private Gtk.Label label16;
        
        private Gtk.Label label17;
        
        private Gtk.SpinButton torrentDownloadRateSpinButton;
        
        private Gtk.SpinButton torrentMaxConnectionsSpinButton;
        
        private Gtk.SpinButton torrentUploadRateSpinButton;
        
        private Gtk.SpinButton torrentUploadSlotSpinButton;
        
        private Gtk.Label GtkLabel11;
        
        private Gtk.Label label13;
        
        private Gtk.Toolbar statusToolbar;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Monsoon.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.FileAction = new Gtk.Action("FileAction", Mono.Unix.Catalog.GetString("_File"), null, null);
            this.FileAction.ShortLabel = Mono.Unix.Catalog.GetString("File");
            w2.Add(this.FileAction, null);
            this.EditAction = new Gtk.Action("EditAction", Mono.Unix.Catalog.GetString("_Edit"), null, null);
            this.EditAction.ShortLabel = Mono.Unix.Catalog.GetString("Edit");
            w2.Add(this.EditAction, null);
            this.ViewAction = new Gtk.Action("ViewAction", Mono.Unix.Catalog.GetString("_View"), null, null);
            this.ViewAction.ShortLabel = Mono.Unix.Catalog.GetString("View");
            w2.Add(this.ViewAction, null);
            this.HelpAction = new Gtk.Action("HelpAction", Mono.Unix.Catalog.GetString("_Help"), null, null);
            this.HelpAction.ShortLabel = Mono.Unix.Catalog.GetString("Help");
            w2.Add(this.HelpAction, null);
            this.About = new Gtk.Action("About", Mono.Unix.Catalog.GetString("_About"), null, "gtk-about");
            this.About.ShortLabel = Mono.Unix.Catalog.GetString("_About");
            w2.Add(this.About, null);
            this.Quit = new Gtk.Action("Quit", Mono.Unix.Catalog.GetString("Quit"), null, "gtk-quit");
            this.Quit.ShortLabel = Mono.Unix.Catalog.GetString("Quit");
            w2.Add(this.Quit, null);
            this.stopTorrentButton = new Gtk.Action("stopTorrentButton", null, Mono.Unix.Catalog.GetString("Stop the torrent"), "gtk-media-stop");
            this.stopTorrentButton.Sensitive = false;
            w2.Add(this.stopTorrentButton, null);
            this.removeTorrentButton = new Gtk.Action("removeTorrentButton", null, Mono.Unix.Catalog.GetString("Remove the torrent"), "gtk-remove");
            this.removeTorrentButton.Sensitive = false;
            w2.Add(this.removeTorrentButton, null);
            this.preferences = new Gtk.Action("preferences", null, Mono.Unix.Catalog.GetString("Open the preferences dialog"), "gtk-preferences");
            w2.Add(this.preferences, null);
            this.deleteTorrentButton = new Gtk.Action("deleteTorrentButton", null, Mono.Unix.Catalog.GetString("Remove the torrent and delete it's data"), "gtk-delete");
            this.deleteTorrentButton.Sensitive = false;
            w2.Add(this.deleteTorrentButton, null);
            this.EditColumns = new Gtk.Action("EditColumns", Mono.Unix.Catalog.GetString("Edit Columns"), null, null);
            this.EditColumns.ShortLabel = Mono.Unix.Catalog.GetString("Columns");
            w2.Add(this.EditColumns, null);
            this.ShowLabels = new Gtk.ToggleAction("ShowLabels", Mono.Unix.Catalog.GetString("Show Labels"), null, null);
            this.ShowLabels.ShortLabel = Mono.Unix.Catalog.GetString("Show Labels");
            w2.Add(this.ShowLabels, null);
            this.ShowDetailedInfo = new Gtk.ToggleAction("ShowDetailedInfo", Mono.Unix.Catalog.GetString("Show Detailed Info"), null, null);
            this.ShowDetailedInfo.ShortLabel = Mono.Unix.Catalog.GetString("Show Detailed Info");
            w2.Add(this.ShowDetailedInfo, null);
            this.OpenTorrent = new Gtk.Action("OpenTorrent", Mono.Unix.Catalog.GetString("_Open Torrent"), Mono.Unix.Catalog.GetString("Open existing torrent file"), "gtk-open");
            this.OpenTorrent.ShortLabel = Mono.Unix.Catalog.GetString("_Open Torrent");
            w2.Add(this.OpenTorrent, null);
            this.startTorrentButton = new Gtk.Action("startTorrentButton", null, Mono.Unix.Catalog.GetString("Start the torrent"), "gtk-media-play");
            w2.Add(this.startTorrentButton, null);
            this.NewTorrent = new Gtk.Action("NewTorrent", Mono.Unix.Catalog.GetString("_New Torrent"), Mono.Unix.Catalog.GetString("Create a new torrent"), "gtk-new");
            this.NewTorrent.ShortLabel = Mono.Unix.Catalog.GetString("_New Torrent");
            w2.Add(this.NewTorrent, null);
            this.Plugins = new Gtk.Action("Plugins", Mono.Unix.Catalog.GetString("Plugins"), Mono.Unix.Catalog.GetString("Open the RSS manager"), "rss");
            this.Plugins.ShortLabel = Mono.Unix.Catalog.GetString("Plugins");
            w2.Add(this.Plugins, null);
            this.ReportBugAction = new Gtk.Action("ReportBugAction", Mono.Unix.Catalog.GetString("Report Bug"), null, null);
            this.ReportBugAction.ShortLabel = Mono.Unix.Catalog.GetString("Report Bug");
            w2.Add(this.ReportBugAction, null);
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "Monsoon.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("Monsoon");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "stock_weather-showers", Gtk.IconSize.Dialog, 48);
            // Container child Monsoon.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><menubar name='menubar1'><menu action='FileAction'><menuitem action='NewTorrent'/><menuitem action='OpenTorrent'/><separator/><menuitem action='Quit'/></menu><menu action='EditAction'><menuitem action='preferences'/></menu><menu action='ViewAction'><menuitem action='EditColumns'/><separator/><menuitem action='ShowLabels'/><menuitem action='ShowDetailedInfo'/></menu><menu action='HelpAction'><menuitem action='About'/><menuitem action='ReportBugAction'/></menu></menubar></ui>");
            this.menubar1 = ((Gtk.MenuBar)(w1.GetWidget("/menubar1")));
            this.menubar1.Name = "menubar1";
            this.vbox1.Add(this.menubar1);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubar1]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem action='NewTorrent'/><toolitem action='OpenTorrent'/><separator/><toolitem action='startTorrentButton'/><toolitem action='stopTorrentButton'/><toolitem action='removeTorrentButton'/><toolitem action='deleteTorrentButton'/><separator/><toolitem action='Plugins'/><toolitem action='preferences'/></toolbar></ui>");
            this.toolbar1 = ((Gtk.Toolbar)(w1.GetWidget("/toolbar1")));
            this.toolbar1.Name = "toolbar1";
            this.toolbar1.ShowArrow = false;
            this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
            this.vbox1.Add(this.toolbar1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox1[this.toolbar1]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hPaned = new Gtk.HPaned();
            this.hPaned.CanFocus = true;
            this.hPaned.Name = "hPaned";
            this.hPaned.Position = 145;
            // Container child hPaned.Gtk.Paned+PanedChild
            this.labelViewScrolledWindow = new Gtk.ScrolledWindow();
            this.labelViewScrolledWindow.CanFocus = true;
            this.labelViewScrolledWindow.Name = "labelViewScrolledWindow";
            this.hPaned.Add(this.labelViewScrolledWindow);
            Gtk.Paned.PanedChild w5 = ((Gtk.Paned.PanedChild)(this.hPaned[this.labelViewScrolledWindow]));
            w5.Resize = false;
            // Container child hPaned.Gtk.Paned+PanedChild
            this.vPaned = new Gtk.VPaned();
            this.vPaned.CanFocus = true;
            this.vPaned.Name = "vPaned";
            this.vPaned.Position = 165;
            // Container child vPaned.Gtk.Paned+PanedChild
            this.torrentViewScrolledWindow = new Gtk.ScrolledWindow();
            this.torrentViewScrolledWindow.CanFocus = true;
            this.torrentViewScrolledWindow.Name = "torrentViewScrolledWindow";
            this.torrentViewScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.vPaned.Add(this.torrentViewScrolledWindow);
            Gtk.Paned.PanedChild w6 = ((Gtk.Paned.PanedChild)(this.vPaned[this.torrentViewScrolledWindow]));
            w6.Resize = false;
            // Container child vPaned.Gtk.Paned+PanedChild
            this.detailNotebook = new Gtk.Notebook();
            this.detailNotebook.CanFocus = true;
            this.detailNotebook.Name = "detailNotebook";
            this.detailNotebook.CurrentPage = 0;
            // Container child detailNotebook.Gtk.Notebook+NotebookChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            Gtk.Viewport w7 = new Gtk.Viewport();
            w7.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport2.Gtk.Container+ContainerChild
            this.vbox4 = new Gtk.VBox();
            this.vbox4.Name = "vbox4";
            this.vbox4.Spacing = 6;
            this.vbox4.BorderWidth = ((uint)(5));
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.statusProgressBarLabel = new Gtk.Label();
            this.statusProgressBarLabel.Name = "statusProgressBarLabel";
            this.statusProgressBarLabel.LabelProp = Mono.Unix.Catalog.GetString("Status: ");
            this.hbox3.Add(this.statusProgressBarLabel);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.hbox3[this.statusProgressBarLabel]));
            w8.Position = 0;
            w8.Expand = false;
            w8.Fill = false;
            // Container child hbox3.Gtk.Box+BoxChild
            this.statusProgressBar = new Gtk.ProgressBar();
            this.statusProgressBar.Name = "statusProgressBar";
            this.statusProgressBar.Text = Mono.Unix.Catalog.GetString(" ");
            this.hbox3.Add(this.statusProgressBar);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.hbox3[this.statusProgressBar]));
            w9.Position = 1;
            this.vbox4.Add(this.hbox3);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox3]));
            w10.Position = 0;
            w10.Expand = false;
            w10.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.WidthRequest = 260;
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment.Name = "GtkAlignment";
            this.GtkAlignment.LeftPadding = ((uint)(12));
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            this.table8 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table8.Name = "table8";
            this.table8.RowSpacing = ((uint)(6));
            this.table8.ColumnSpacing = ((uint)(6));
            // Container child table8.Gtk.Table+TableChild
            this.downloadedValueLabel = new Gtk.Label();
            this.downloadedValueLabel.Name = "downloadedValueLabel";
            this.downloadedValueLabel.Xalign = 0F;
            this.downloadedValueLabel.LabelProp = "";
            this.table8.Add(this.downloadedValueLabel);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table8[this.downloadedValueLabel]));
            w11.TopAttach = ((uint)(1));
            w11.BottomAttach = ((uint)(2));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.elapsedTimeLabel = new Gtk.Label();
            this.elapsedTimeLabel.Name = "elapsedTimeLabel";
            this.elapsedTimeLabel.Xalign = 0F;
            this.elapsedTimeLabel.LabelProp = Mono.Unix.Catalog.GetString("Elapsed Time:");
            this.table8.Add(this.elapsedTimeLabel);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table8[this.elapsedTimeLabel]));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.elapsedTimeValueLabel = new Gtk.Label();
            this.elapsedTimeValueLabel.Name = "elapsedTimeValueLabel";
            this.elapsedTimeValueLabel.Xalign = 0F;
            this.elapsedTimeValueLabel.LabelProp = "";
            this.table8.Add(this.elapsedTimeValueLabel);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table8[this.elapsedTimeValueLabel]));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.hashFailsLabel = new Gtk.Label();
            this.hashFailsLabel.Name = "hashFailsLabel";
            this.hashFailsLabel.Xalign = 0F;
            this.hashFailsLabel.LabelProp = "";
            this.table8.Add(this.hashFailsLabel);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table8[this.hashFailsLabel]));
            w14.TopAttach = ((uint)(3));
            w14.BottomAttach = ((uint)(4));
            w14.LeftAttach = ((uint)(1));
            w14.RightAttach = ((uint)(2));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.label21 = new Gtk.Label();
            this.label21.Name = "label21";
            this.label21.Xalign = 0F;
            this.label21.LabelProp = Mono.Unix.Catalog.GetString("Downloaded:");
            this.table8.Add(this.label21);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table8[this.label21]));
            w15.TopAttach = ((uint)(1));
            w15.BottomAttach = ((uint)(2));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.label22 = new Gtk.Label();
            this.label22.Name = "label22";
            this.label22.Xalign = 0F;
            this.label22.LabelProp = Mono.Unix.Catalog.GetString("Uploaded:");
            this.table8.Add(this.label22);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table8[this.label22]));
            w16.TopAttach = ((uint)(2));
            w16.BottomAttach = ((uint)(3));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Hash Fails:");
            this.table8.Add(this.label3);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table8[this.label3]));
            w17.TopAttach = ((uint)(3));
            w17.BottomAttach = ((uint)(4));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Swarm Speed:");
            this.table8.Add(this.label5);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table8[this.label5]));
            w18.TopAttach = ((uint)(4));
            w18.BottomAttach = ((uint)(5));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.swarmSpeedLabel = new Gtk.Label();
            this.swarmSpeedLabel.Name = "swarmSpeedLabel";
            this.swarmSpeedLabel.Xalign = 0F;
            this.swarmSpeedLabel.LabelProp = "";
            this.table8.Add(this.swarmSpeedLabel);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table8[this.swarmSpeedLabel]));
            w19.TopAttach = ((uint)(4));
            w19.BottomAttach = ((uint)(5));
            w19.LeftAttach = ((uint)(1));
            w19.RightAttach = ((uint)(2));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table8.Gtk.Table+TableChild
            this.uploadedValueLabel = new Gtk.Label();
            this.uploadedValueLabel.Name = "uploadedValueLabel";
            this.uploadedValueLabel.Xalign = 0F;
            this.uploadedValueLabel.LabelProp = "";
            this.table8.Add(this.uploadedValueLabel);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table8[this.uploadedValueLabel]));
            w20.TopAttach = ((uint)(2));
            w20.BottomAttach = ((uint)(3));
            w20.LeftAttach = ((uint)(1));
            w20.RightAttach = ((uint)(2));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment.Add(this.table8);
            this.frame1.Add(this.GtkAlignment);
            this.GtkLabel6 = new Gtk.Label();
            this.GtkLabel6.Name = "GtkLabel6";
            this.GtkLabel6.LabelProp = Mono.Unix.Catalog.GetString("<b>Transfer</b>");
            this.GtkLabel6.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel6;
            this.hbox1.Add(this.frame1);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame1]));
            w23.Position = 0;
            w23.Expand = false;
            w23.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table7 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table7.Name = "table7";
            this.table7.RowSpacing = ((uint)(6));
            this.table7.ColumnSpacing = ((uint)(6));
            // Container child table7.Gtk.Table+TableChild
            this.label19 = new Gtk.Label();
            this.label19.Name = "label19";
            this.label19.Xalign = 0F;
            this.label19.LabelProp = Mono.Unix.Catalog.GetString("Update In:");
            this.table7.Add(this.label19);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table7[this.label19]));
            w24.TopAttach = ((uint)(3));
            w24.BottomAttach = ((uint)(4));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.label20 = new Gtk.Label();
            this.label20.Name = "label20";
            this.label20.Xalign = 0F;
            this.label20.LabelProp = Mono.Unix.Catalog.GetString("Status:");
            this.table7.Add(this.label20);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table7[this.label20]));
            w25.TopAttach = ((uint)(1));
            w25.BottomAttach = ((uint)(2));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.label23 = new Gtk.Label();
            this.label23.Name = "label23";
            this.label23.Xalign = 0F;
            this.label23.LabelProp = Mono.Unix.Catalog.GetString("Message:");
            this.table7.Add(this.label23);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table7[this.label23]));
            w26.TopAttach = ((uint)(4));
            w26.BottomAttach = ((uint)(5));
            w26.XOptions = ((Gtk.AttachOptions)(4));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Last Updated:");
            this.table7.Add(this.label4);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table7[this.label4]));
            w27.TopAttach = ((uint)(2));
            w27.BottomAttach = ((uint)(3));
            w27.XOptions = ((Gtk.AttachOptions)(4));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 0F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("URL:");
            this.table7.Add(this.label8);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table7[this.label8]));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.lastUpdatedLabel = new Gtk.Label();
            this.lastUpdatedLabel.Name = "lastUpdatedLabel";
            this.lastUpdatedLabel.Xalign = 0F;
            this.lastUpdatedLabel.LabelProp = "";
            this.table7.Add(this.lastUpdatedLabel);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table7[this.lastUpdatedLabel]));
            w29.TopAttach = ((uint)(2));
            w29.BottomAttach = ((uint)(3));
            w29.LeftAttach = ((uint)(1));
            w29.RightAttach = ((uint)(2));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.messageLabel = new Gtk.Label();
            this.messageLabel.Name = "messageLabel";
            this.messageLabel.Xalign = 0F;
            this.messageLabel.LabelProp = "";
            this.messageLabel.Wrap = true;
            this.table7.Add(this.messageLabel);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table7[this.messageLabel]));
            w30.TopAttach = ((uint)(4));
            w30.BottomAttach = ((uint)(5));
            w30.LeftAttach = ((uint)(1));
            w30.RightAttach = ((uint)(2));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.trackerStatusValueLabel = new Gtk.Label();
            this.trackerStatusValueLabel.Name = "trackerStatusValueLabel";
            this.trackerStatusValueLabel.Xalign = 0F;
            this.trackerStatusValueLabel.LabelProp = "";
            this.table7.Add(this.trackerStatusValueLabel);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table7[this.trackerStatusValueLabel]));
            w31.TopAttach = ((uint)(1));
            w31.BottomAttach = ((uint)(2));
            w31.LeftAttach = ((uint)(1));
            w31.RightAttach = ((uint)(2));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.trackerUrlValueLabel = new Gtk.Label();
            this.trackerUrlValueLabel.Name = "trackerUrlValueLabel";
            this.trackerUrlValueLabel.Xalign = 0F;
            this.trackerUrlValueLabel.LabelProp = "";
            this.table7.Add(this.trackerUrlValueLabel);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table7[this.trackerUrlValueLabel]));
            w32.LeftAttach = ((uint)(1));
            w32.RightAttach = ((uint)(2));
            w32.XOptions = ((Gtk.AttachOptions)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table7.Gtk.Table+TableChild
            this.updateInLabel = new Gtk.Label();
            this.updateInLabel.Name = "updateInLabel";
            this.updateInLabel.Xalign = 0F;
            this.updateInLabel.LabelProp = "";
            this.table7.Add(this.updateInLabel);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table7[this.updateInLabel]));
            w33.TopAttach = ((uint)(3));
            w33.BottomAttach = ((uint)(4));
            w33.LeftAttach = ((uint)(1));
            w33.RightAttach = ((uint)(2));
            w33.XOptions = ((Gtk.AttachOptions)(4));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table7);
            this.frame2.Add(this.GtkAlignment1);
            this.GtkLabel7 = new Gtk.Label();
            this.GtkLabel7.Name = "GtkLabel7";
            this.GtkLabel7.LabelProp = Mono.Unix.Catalog.GetString("<b>Tracker</b>");
            this.GtkLabel7.UseMarkup = true;
            this.frame2.LabelWidget = this.GtkLabel7;
            this.hbox1.Add(this.frame2);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.hbox1[this.frame2]));
            w36.Position = 1;
            w36.Expand = false;
            w36.Fill = false;
            this.vbox4.Add(this.hbox1);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox4[this.hbox1]));
            w37.Position = 1;
            w37.Expand = false;
            w37.Fill = false;
            // Container child vbox4.Gtk.Box+BoxChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame3.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.table9 = new Gtk.Table(((uint)(4)), ((uint)(2)), false);
            this.table9.Name = "table9";
            this.table9.RowSpacing = ((uint)(6));
            this.table9.ColumnSpacing = ((uint)(6));
            // Container child table9.Gtk.Table+TableChild
            this.commentValueLabel = new Gtk.Label();
            this.commentValueLabel.Name = "commentValueLabel";
            this.commentValueLabel.Xalign = 0F;
            this.commentValueLabel.LabelProp = "";
            this.table9.Add(this.commentValueLabel);
            Gtk.Table.TableChild w38 = ((Gtk.Table.TableChild)(this.table9[this.commentValueLabel]));
            w38.TopAttach = ((uint)(3));
            w38.BottomAttach = ((uint)(4));
            w38.LeftAttach = ((uint)(1));
            w38.RightAttach = ((uint)(2));
            w38.XOptions = ((Gtk.AttachOptions)(4));
            w38.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table9.Gtk.Table+TableChild
            this.createdOnValueLabel = new Gtk.Label();
            this.createdOnValueLabel.Name = "createdOnValueLabel";
            this.createdOnValueLabel.Xalign = 0F;
            this.createdOnValueLabel.LabelProp = "";
            this.table9.Add(this.createdOnValueLabel);
            Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table9[this.createdOnValueLabel]));
            w39.TopAttach = ((uint)(2));
            w39.BottomAttach = ((uint)(3));
            w39.LeftAttach = ((uint)(1));
            w39.RightAttach = ((uint)(2));
            w39.XOptions = ((Gtk.AttachOptions)(4));
            w39.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table9.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xalign = 0F;
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Size:");
            this.table9.Add(this.label10);
            Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table9[this.label10]));
            w40.TopAttach = ((uint)(1));
            w40.BottomAttach = ((uint)(2));
            w40.XOptions = ((Gtk.AttachOptions)(4));
            w40.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table9.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.Xalign = 0F;
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Created on:");
            this.table9.Add(this.label11);
            Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table9[this.label11]));
            w41.TopAttach = ((uint)(2));
            w41.BottomAttach = ((uint)(3));
            w41.XOptions = ((Gtk.AttachOptions)(4));
            w41.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table9.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.Xalign = 0F;
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("Comment:");
            this.table9.Add(this.label12);
            Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table9[this.label12]));
            w42.TopAttach = ((uint)(3));
            w42.BottomAttach = ((uint)(4));
            w42.XOptions = ((Gtk.AttachOptions)(4));
            w42.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table9.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Save path:");
            this.table9.Add(this.label7);
            Gtk.Table.TableChild w43 = ((Gtk.Table.TableChild)(this.table9[this.label7]));
            w43.XOptions = ((Gtk.AttachOptions)(4));
            w43.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table9.Gtk.Table+TableChild
            this.savePathValueLabel = new Gtk.Label();
            this.savePathValueLabel.Name = "savePathValueLabel";
            this.savePathValueLabel.Xalign = 0F;
            this.savePathValueLabel.LabelProp = "";
            this.table9.Add(this.savePathValueLabel);
            Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.table9[this.savePathValueLabel]));
            w44.LeftAttach = ((uint)(1));
            w44.RightAttach = ((uint)(2));
            w44.XOptions = ((Gtk.AttachOptions)(4));
            w44.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table9.Gtk.Table+TableChild
            this.sizeValueLabel = new Gtk.Label();
            this.sizeValueLabel.Name = "sizeValueLabel";
            this.sizeValueLabel.Xalign = 0F;
            this.sizeValueLabel.LabelProp = "";
            this.table9.Add(this.sizeValueLabel);
            Gtk.Table.TableChild w45 = ((Gtk.Table.TableChild)(this.table9[this.sizeValueLabel]));
            w45.TopAttach = ((uint)(1));
            w45.BottomAttach = ((uint)(2));
            w45.LeftAttach = ((uint)(1));
            w45.RightAttach = ((uint)(2));
            w45.XOptions = ((Gtk.AttachOptions)(4));
            w45.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment2.Add(this.table9);
            this.frame3.Add(this.GtkAlignment2);
            this.GtkLabel8 = new Gtk.Label();
            this.GtkLabel8.Name = "GtkLabel8";
            this.GtkLabel8.LabelProp = Mono.Unix.Catalog.GetString("<b>General</b>");
            this.GtkLabel8.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel8;
            this.vbox4.Add(this.frame3);
            Gtk.Box.BoxChild w48 = ((Gtk.Box.BoxChild)(this.vbox4[this.frame3]));
            w48.Position = 2;
            w48.Expand = false;
            w48.Fill = false;
            w7.Add(this.vbox4);
            this.scrolledwindow1.Add(w7);
            this.detailNotebook.Add(this.scrolledwindow1);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("General");
            this.detailNotebook.SetTabLabel(this.scrolledwindow1, this.label1);
            this.label1.ShowAll();
            // Container child detailNotebook.Gtk.Notebook+NotebookChild
            this.filesScrolledWindow = new Gtk.ScrolledWindow();
            this.filesScrolledWindow.CanFocus = true;
            this.filesScrolledWindow.Name = "filesScrolledWindow";
            this.filesScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.detailNotebook.Add(this.filesScrolledWindow);
            Gtk.Notebook.NotebookChild w52 = ((Gtk.Notebook.NotebookChild)(this.detailNotebook[this.filesScrolledWindow]));
            w52.Position = 1;
            // Notebook tab
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Files");
            this.detailNotebook.SetTabLabel(this.filesScrolledWindow, this.label9);
            this.label9.ShowAll();
            // Container child detailNotebook.Gtk.Notebook+NotebookChild
            this.piecesScrolledWindow = new Gtk.ScrolledWindow();
            this.piecesScrolledWindow.CanFocus = true;
            this.piecesScrolledWindow.Name = "piecesScrolledWindow";
            this.piecesScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.detailNotebook.Add(this.piecesScrolledWindow);
            Gtk.Notebook.NotebookChild w53 = ((Gtk.Notebook.NotebookChild)(this.detailNotebook[this.piecesScrolledWindow]));
            w53.Position = 2;
            // Notebook tab
            this.label18 = new Gtk.Label();
            this.label18.Name = "label18";
            this.label18.LabelProp = Mono.Unix.Catalog.GetString("Pieces");
            this.detailNotebook.SetTabLabel(this.piecesScrolledWindow, this.label18);
            this.label18.ShowAll();
            // Container child detailNotebook.Gtk.Notebook+NotebookChild
            this.peersScrolledWindow = new Gtk.ScrolledWindow();
            this.peersScrolledWindow.CanFocus = true;
            this.peersScrolledWindow.Name = "peersScrolledWindow";
            this.peersScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.detailNotebook.Add(this.peersScrolledWindow);
            Gtk.Notebook.NotebookChild w54 = ((Gtk.Notebook.NotebookChild)(this.detailNotebook[this.peersScrolledWindow]));
            w54.Position = 3;
            // Notebook tab
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Peers");
            this.detailNotebook.SetTabLabel(this.peersScrolledWindow, this.label6);
            this.label6.ShowAll();
            // Container child detailNotebook.Gtk.Notebook+NotebookChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow2.Gtk.Container+ContainerChild
            Gtk.Viewport w55 = new Gtk.Viewport();
            w55.ShadowType = ((Gtk.ShadowType)(0));
            // Container child GtkViewport5.Gtk.Container+ContainerChild
            this.hbox13 = new Gtk.HBox();
            this.hbox13.Name = "hbox13";
            this.hbox13.Spacing = 6;
            // Container child hbox13.Gtk.Box+BoxChild
            this.vbox6 = new Gtk.VBox();
            this.vbox6.Name = "vbox6";
            this.vbox6.Spacing = 6;
            // Container child vbox6.Gtk.Box+BoxChild
            this.frame5 = new Gtk.Frame();
            this.frame5.Name = "frame5";
            this.frame5.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame5.Gtk.Container+ContainerChild
            this.GtkAlignment4 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment4.Name = "GtkAlignment4";
            this.GtkAlignment4.LeftPadding = ((uint)(12));
            // Container child GtkAlignment4.Gtk.Container+ContainerChild
            this.table2 = new Gtk.Table(((uint)(5)), ((uint)(2)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.label14 = new Gtk.Label();
            this.label14.Name = "label14";
            this.label14.Xalign = 0F;
            this.label14.LabelProp = Mono.Unix.Catalog.GetString("Maximum upload rate:");
            this.table2.Add(this.label14);
            Gtk.Table.TableChild w56 = ((Gtk.Table.TableChild)(this.table2[this.label14]));
            w56.XOptions = ((Gtk.AttachOptions)(4));
            w56.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label15 = new Gtk.Label();
            this.label15.Name = "label15";
            this.label15.Xalign = 0F;
            this.label15.LabelProp = Mono.Unix.Catalog.GetString("Maximum download rate:");
            this.table2.Add(this.label15);
            Gtk.Table.TableChild w57 = ((Gtk.Table.TableChild)(this.table2[this.label15]));
            w57.TopAttach = ((uint)(1));
            w57.BottomAttach = ((uint)(2));
            w57.XOptions = ((Gtk.AttachOptions)(4));
            w57.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label16 = new Gtk.Label();
            this.label16.Name = "label16";
            this.label16.Xalign = 0F;
            this.label16.LabelProp = Mono.Unix.Catalog.GetString("Maximum connections:");
            this.table2.Add(this.label16);
            Gtk.Table.TableChild w58 = ((Gtk.Table.TableChild)(this.table2[this.label16]));
            w58.TopAttach = ((uint)(2));
            w58.BottomAttach = ((uint)(3));
            w58.XOptions = ((Gtk.AttachOptions)(4));
            w58.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.label17 = new Gtk.Label();
            this.label17.Name = "label17";
            this.label17.Xalign = 0F;
            this.label17.LabelProp = Mono.Unix.Catalog.GetString("Upload slots:");
            this.table2.Add(this.label17);
            Gtk.Table.TableChild w59 = ((Gtk.Table.TableChild)(this.table2[this.label17]));
            w59.TopAttach = ((uint)(3));
            w59.BottomAttach = ((uint)(4));
            w59.XOptions = ((Gtk.AttachOptions)(4));
            w59.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.torrentDownloadRateSpinButton = new Gtk.SpinButton(0, 100, 1);
            this.torrentDownloadRateSpinButton.CanFocus = true;
            this.torrentDownloadRateSpinButton.Name = "torrentDownloadRateSpinButton";
            this.torrentDownloadRateSpinButton.Adjustment.PageIncrement = 10;
            this.torrentDownloadRateSpinButton.ClimbRate = 1;
            this.torrentDownloadRateSpinButton.Numeric = true;
            this.table2.Add(this.torrentDownloadRateSpinButton);
            Gtk.Table.TableChild w60 = ((Gtk.Table.TableChild)(this.table2[this.torrentDownloadRateSpinButton]));
            w60.TopAttach = ((uint)(1));
            w60.BottomAttach = ((uint)(2));
            w60.LeftAttach = ((uint)(1));
            w60.RightAttach = ((uint)(2));
            w60.XOptions = ((Gtk.AttachOptions)(4));
            w60.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.torrentMaxConnectionsSpinButton = new Gtk.SpinButton(0, 100, 1);
            this.torrentMaxConnectionsSpinButton.CanFocus = true;
            this.torrentMaxConnectionsSpinButton.Name = "torrentMaxConnectionsSpinButton";
            this.torrentMaxConnectionsSpinButton.Adjustment.PageIncrement = 10;
            this.torrentMaxConnectionsSpinButton.ClimbRate = 1;
            this.torrentMaxConnectionsSpinButton.Numeric = true;
            this.table2.Add(this.torrentMaxConnectionsSpinButton);
            Gtk.Table.TableChild w61 = ((Gtk.Table.TableChild)(this.table2[this.torrentMaxConnectionsSpinButton]));
            w61.TopAttach = ((uint)(2));
            w61.BottomAttach = ((uint)(3));
            w61.LeftAttach = ((uint)(1));
            w61.RightAttach = ((uint)(2));
            w61.XOptions = ((Gtk.AttachOptions)(4));
            w61.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.torrentUploadRateSpinButton = new Gtk.SpinButton(0, 100, 1);
            this.torrentUploadRateSpinButton.CanFocus = true;
            this.torrentUploadRateSpinButton.Name = "torrentUploadRateSpinButton";
            this.torrentUploadRateSpinButton.Adjustment.PageIncrement = 10;
            this.torrentUploadRateSpinButton.ClimbRate = 1;
            this.torrentUploadRateSpinButton.Numeric = true;
            this.table2.Add(this.torrentUploadRateSpinButton);
            Gtk.Table.TableChild w62 = ((Gtk.Table.TableChild)(this.table2[this.torrentUploadRateSpinButton]));
            w62.LeftAttach = ((uint)(1));
            w62.RightAttach = ((uint)(2));
            w62.XOptions = ((Gtk.AttachOptions)(4));
            w62.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.torrentUploadSlotSpinButton = new Gtk.SpinButton(0, 100, 1);
            this.torrentUploadSlotSpinButton.CanFocus = true;
            this.torrentUploadSlotSpinButton.Name = "torrentUploadSlotSpinButton";
            this.torrentUploadSlotSpinButton.Adjustment.PageIncrement = 10;
            this.torrentUploadSlotSpinButton.ClimbRate = 1;
            this.torrentUploadSlotSpinButton.Numeric = true;
            this.table2.Add(this.torrentUploadSlotSpinButton);
            Gtk.Table.TableChild w63 = ((Gtk.Table.TableChild)(this.table2[this.torrentUploadSlotSpinButton]));
            w63.TopAttach = ((uint)(3));
            w63.BottomAttach = ((uint)(4));
            w63.LeftAttach = ((uint)(1));
            w63.RightAttach = ((uint)(2));
            w63.XOptions = ((Gtk.AttachOptions)(4));
            w63.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment4.Add(this.table2);
            this.frame5.Add(this.GtkAlignment4);
            this.GtkLabel11 = new Gtk.Label();
            this.GtkLabel11.Name = "GtkLabel11";
            this.GtkLabel11.LabelProp = Mono.Unix.Catalog.GetString("<b>Bandwidth</b>");
            this.GtkLabel11.UseMarkup = true;
            this.frame5.LabelWidget = this.GtkLabel11;
            this.vbox6.Add(this.frame5);
            Gtk.Box.BoxChild w66 = ((Gtk.Box.BoxChild)(this.vbox6[this.frame5]));
            w66.Position = 0;
            this.hbox13.Add(this.vbox6);
            Gtk.Box.BoxChild w67 = ((Gtk.Box.BoxChild)(this.hbox13[this.vbox6]));
            w67.Position = 0;
            w67.Expand = false;
            w67.Fill = false;
            w55.Add(this.hbox13);
            this.scrolledwindow2.Add(w55);
            this.detailNotebook.Add(this.scrolledwindow2);
            Gtk.Notebook.NotebookChild w70 = ((Gtk.Notebook.NotebookChild)(this.detailNotebook[this.scrolledwindow2]));
            w70.Position = 4;
            // Notebook tab
            this.label13 = new Gtk.Label();
            this.label13.Name = "label13";
            this.label13.LabelProp = Mono.Unix.Catalog.GetString("Options");
            this.detailNotebook.SetTabLabel(this.scrolledwindow2, this.label13);
            this.label13.ShowAll();
            this.vPaned.Add(this.detailNotebook);
            this.hPaned.Add(this.vPaned);
            this.vbox1.Add(this.hPaned);
            Gtk.Box.BoxChild w73 = ((Gtk.Box.BoxChild)(this.vbox1[this.hPaned]));
            w73.Position = 2;
            // Container child vbox1.Gtk.Box+BoxChild
            w1.AddUiFromString("<ui><toolbar name='statusToolbar'/></ui>");
            this.statusToolbar = ((Gtk.Toolbar)(w1.GetWidget("/statusToolbar")));
            this.statusToolbar.Name = "statusToolbar";
            this.statusToolbar.ShowArrow = false;
            this.statusToolbar.ToolbarStyle = ((Gtk.ToolbarStyle)(0));
            this.statusToolbar.IconSize = ((Gtk.IconSize)(1));
            this.vbox1.Add(this.statusToolbar);
            Gtk.Box.BoxChild w74 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusToolbar]));
            w74.Position = 3;
            w74.Expand = false;
            w74.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 765;
            this.DefaultHeight = 658;
            this.Hide();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.About.Activated += new System.EventHandler(this.OnAboutActivated);
            this.Quit.Activated += new System.EventHandler(this.OnQuitActivated);
            this.stopTorrentButton.Activated += new System.EventHandler(this.OnStopTorrentActivated);
            this.removeTorrentButton.Activated += new System.EventHandler(this.OnRemoveTorrentButtonActivated);
            this.preferences.Activated += new System.EventHandler(this.OnPreferencesActivated);
            this.deleteTorrentButton.Activated += new System.EventHandler(this.OnDeleteTorrentButtonActivated);
            this.EditColumns.Activated += new System.EventHandler(this.OnColumnsActivated);
            this.ShowLabels.Activated += new System.EventHandler(this.OnShowLabelsActivated);
            this.ShowDetailedInfo.Activated += new System.EventHandler(this.OnShowDetailedInfoActivated);
            this.OpenTorrent.Activated += new System.EventHandler(this.OnOpenActivated);
            this.startTorrentButton.Activated += new System.EventHandler(this.OnStartTorrentActivated);
            this.NewTorrent.Activated += new System.EventHandler(this.OnNewActivated);
            this.Plugins.Activated += new System.EventHandler(this.OnPluginsActivated);
            this.ReportBugAction.Activated += new System.EventHandler(this.OnReportBugActivated);
        }
    }
}
