// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monsoon {
    
    
    public partial class PreferencesDialog {
        
        private Gtk.Notebook prefNotebook;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Frame frame7;
        
        private Gtk.Alignment GtkAlignment10;
        
        private Gtk.Table table1;
        
        private Gtk.CheckButton enableNotificationsCheckButton;
        
        private Gtk.CheckButton enableTrayCheckButton;
        
        private Gtk.CheckButton minimizeTrayCheckButton;
        
        private Gtk.Label GtkLabel13;
        
        private Gtk.Label label2;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Frame frame1;
        
        private Gtk.Alignment GtkAlignment1;
        
        private Gtk.Table table3;
        
        private Gtk.Label maxConnectionsLabel;
        
        private Gtk.SpinButton maxConnectionsSpinButton;
        
        private Gtk.Label portLabel;
        
        private Gtk.SpinButton portSpinButton;
        
        private Gtk.CheckButton upnpCheckBox;
        
        private Gtk.Label GtkLabel5;
        
        private Gtk.Frame frame2;
        
        private Gtk.Alignment GtkAlignment2;
        
        private Gtk.Table table4;
        
        private Gtk.Label downloadSpeedLabel;
        
        private Gtk.SpinButton maxDownloadSpeedSpinButton;
        
        private Gtk.SpinButton maxUploadSpeedSpinButton;
        
        private Gtk.Label uploadSpeedLabel;
        
        private Gtk.Label bandwidthPanelLabel;
        
        private Gtk.Label label3;
        
        private Gtk.VBox vbox5;
        
        private Gtk.Frame frame4;
        
        private Gtk.Alignment GtkAlignment5;
        
        private Gtk.VBox vbox8;
        
        private Gtk.CheckButton startNewTorrentsCheckBox;
        
        private Gtk.Label GtkLabel7;
        
        private Gtk.Frame foldersFrame;
        
        private Gtk.Alignment GtkAlignment3;
        
        private Gtk.Table foldersTable;
        
        private Gtk.Label label1;
        
        private Gtk.Label label7;
        
        private Gtk.Label GtkLabel6;
        
        private Gtk.Frame frame3;
        
        private Gtk.Alignment GtkAlignment4;
        
        private Gtk.VBox vbox7;
        
        private Gtk.CheckButton importTorrentsCheckBox;
        
        private Gtk.CheckButton removeOnImportCheckButton;
        
        private Gtk.HBox importDirectoryHbox;
        
        private Gtk.Label label6;
        
        private Gtk.Label GtkLabel11;
        
        private Gtk.Label label4;
        
        private Gtk.VBox vbox9;
        
        private Gtk.Frame frame5;
        
        private Gtk.Alignment GtkAlignment6;
        
        private Gtk.HBox iconHbox;
        
        private Gtk.HBox iconEntryBox;
        
        private Gtk.VBox vbox10;
        
        private Gtk.HBox hbox6;
        
        private Gtk.Entry nameEntry;
        
        private Gtk.Label label8;
        
        private Gtk.VBox vbox12;
        
        private Gtk.Label GtkLabel12;
        
        private Gtk.Frame frame6;
        
        private Gtk.Alignment GtkAlignment7;
        
        private Gtk.HBox hbox8;
        
        private Gtk.ScrolledWindow labelScrolledWindow;
        
        private Gtk.VBox vbox11;
        
        private Gtk.Button addLabelButton;
        
        private Gtk.Button removeLabelButton;
        
        private Gtk.Label GtkLabel15;
        
        private Gtk.Label label5;
        
        private Gtk.Button button478;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Monsoon.PreferencesDialog
            this.Events = ((Gdk.EventMask)(256));
            this.Name = "Monsoon.PreferencesDialog";
            this.Title = Mono.Unix.Catalog.GetString("Monsoon Preferences");
            // Internal child Monsoon.PreferencesDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Events = ((Gdk.EventMask)(256));
            w1.Name = "dialog_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog_VBox.Gtk.Box+BoxChild
            this.prefNotebook = new Gtk.Notebook();
            this.prefNotebook.CanFocus = true;
            this.prefNotebook.Name = "prefNotebook";
            this.prefNotebook.CurrentPage = 3;
            // Container child prefNotebook.Gtk.Notebook+NotebookChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.frame7 = new Gtk.Frame();
            this.frame7.Name = "frame7";
            this.frame7.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame7.Gtk.Container+ContainerChild
            this.GtkAlignment10 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment10.Name = "GtkAlignment10";
            this.GtkAlignment10.LeftPadding = ((uint)(12));
            // Container child GtkAlignment10.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(1)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.enableNotificationsCheckButton = new Gtk.CheckButton();
            this.enableNotificationsCheckButton.CanFocus = true;
            this.enableNotificationsCheckButton.Name = "enableNotificationsCheckButton";
            this.enableNotificationsCheckButton.Label = Mono.Unix.Catalog.GetString("Enable notifications on torrent completion");
            this.enableNotificationsCheckButton.DrawIndicator = true;
            this.enableNotificationsCheckButton.UseUnderline = true;
            this.table1.Add(this.enableNotificationsCheckButton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.enableNotificationsCheckButton]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.enableTrayCheckButton = new Gtk.CheckButton();
            this.enableTrayCheckButton.CanFocus = true;
            this.enableTrayCheckButton.Name = "enableTrayCheckButton";
            this.enableTrayCheckButton.Label = Mono.Unix.Catalog.GetString("Enable icon");
            this.enableTrayCheckButton.DrawIndicator = true;
            this.enableTrayCheckButton.UseUnderline = true;
            this.table1.Add(this.enableTrayCheckButton);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.enableTrayCheckButton]));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.minimizeTrayCheckButton = new Gtk.CheckButton();
            this.minimizeTrayCheckButton.CanFocus = true;
            this.minimizeTrayCheckButton.Name = "minimizeTrayCheckButton";
            this.minimizeTrayCheckButton.Label = Mono.Unix.Catalog.GetString("Minimize to notification area on close");
            this.minimizeTrayCheckButton.DrawIndicator = true;
            this.minimizeTrayCheckButton.UseUnderline = true;
            this.table1.Add(this.minimizeTrayCheckButton);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.minimizeTrayCheckButton]));
            w4.TopAttach = ((uint)(1));
            w4.BottomAttach = ((uint)(2));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment10.Add(this.table1);
            this.frame7.Add(this.GtkAlignment10);
            this.GtkLabel13 = new Gtk.Label();
            this.GtkLabel13.Name = "GtkLabel13";
            this.GtkLabel13.LabelProp = Mono.Unix.Catalog.GetString("<b>Notification Area Icon</b>");
            this.GtkLabel13.UseMarkup = true;
            this.frame7.LabelWidget = this.GtkLabel13;
            this.vbox3.Add(this.frame7);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox3[this.frame7]));
            w7.Position = 0;
            w7.Expand = false;
            w7.Fill = false;
            this.prefNotebook.Add(this.vbox3);
            // Notebook tab
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("General");
            this.prefNotebook.SetTabLabel(this.vbox3, this.label2);
            this.label2.ShowAll();
            // Container child prefNotebook.Gtk.Notebook+NotebookChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.BorderWidth = ((uint)(5));
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame1 = new Gtk.Frame();
            this.frame1.Name = "frame1";
            this.frame1.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame1.Gtk.Container+ContainerChild
            this.GtkAlignment1 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment1.Name = "GtkAlignment1";
            this.GtkAlignment1.LeftPadding = ((uint)(12));
            // Container child GtkAlignment1.Gtk.Container+ContainerChild
            this.table3 = new Gtk.Table(((uint)(2)), ((uint)(3)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.maxConnectionsLabel = new Gtk.Label();
            this.maxConnectionsLabel.Name = "maxConnectionsLabel";
            this.maxConnectionsLabel.Xalign = 0F;
            this.maxConnectionsLabel.LabelProp = Mono.Unix.Catalog.GetString("Maximum connections: ");
            this.table3.Add(this.maxConnectionsLabel);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table3[this.maxConnectionsLabel]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.maxConnectionsSpinButton = new Gtk.SpinButton(0, 1000, 1);
            this.maxConnectionsSpinButton.CanFocus = true;
            this.maxConnectionsSpinButton.Name = "maxConnectionsSpinButton";
            this.maxConnectionsSpinButton.Adjustment.PageIncrement = 10;
            this.maxConnectionsSpinButton.ClimbRate = 1;
            this.maxConnectionsSpinButton.Numeric = true;
            this.table3.Add(this.maxConnectionsSpinButton);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table3[this.maxConnectionsSpinButton]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.portLabel = new Gtk.Label();
            this.portLabel.Name = "portLabel";
            this.portLabel.Xalign = 0F;
            this.portLabel.LabelProp = Mono.Unix.Catalog.GetString("Listen port: ");
            this.table3.Add(this.portLabel);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table3[this.portLabel]));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.portSpinButton = new Gtk.SpinButton(0, 65535, 1);
            this.portSpinButton.CanFocus = true;
            this.portSpinButton.Name = "portSpinButton";
            this.portSpinButton.Adjustment.PageIncrement = 10;
            this.portSpinButton.ClimbRate = 1;
            this.portSpinButton.Numeric = true;
            this.table3.Add(this.portSpinButton);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table3[this.portSpinButton]));
            w12.LeftAttach = ((uint)(1));
            w12.RightAttach = ((uint)(2));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.upnpCheckBox = new Gtk.CheckButton();
            this.upnpCheckBox.CanFocus = true;
            this.upnpCheckBox.Name = "upnpCheckBox";
            this.upnpCheckBox.Label = Mono.Unix.Catalog.GetString("Enable UPnP");
            this.upnpCheckBox.DrawIndicator = true;
            this.upnpCheckBox.UseUnderline = true;
            this.table3.Add(this.upnpCheckBox);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table3[this.upnpCheckBox]));
            w13.LeftAttach = ((uint)(2));
            w13.RightAttach = ((uint)(3));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment1.Add(this.table3);
            this.frame1.Add(this.GtkAlignment1);
            this.GtkLabel5 = new Gtk.Label();
            this.GtkLabel5.Name = "GtkLabel5";
            this.GtkLabel5.LabelProp = Mono.Unix.Catalog.GetString("<b>Ports</b>");
            this.GtkLabel5.UseMarkup = true;
            this.frame1.LabelWidget = this.GtkLabel5;
            this.vbox2.Add(this.frame1);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
            w16.Position = 0;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.frame2 = new Gtk.Frame();
            this.frame2.Name = "frame2";
            this.frame2.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame2.Gtk.Container+ContainerChild
            this.GtkAlignment2 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment2.Name = "GtkAlignment2";
            this.GtkAlignment2.LeftPadding = ((uint)(12));
            // Container child GtkAlignment2.Gtk.Container+ContainerChild
            this.table4 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.downloadSpeedLabel = new Gtk.Label();
            this.downloadSpeedLabel.Name = "downloadSpeedLabel";
            this.downloadSpeedLabel.Xalign = 0F;
            this.downloadSpeedLabel.LabelProp = Mono.Unix.Catalog.GetString("Maximum download speed: ");
            this.table4.Add(this.downloadSpeedLabel);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table4[this.downloadSpeedLabel]));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.maxDownloadSpeedSpinButton = new Gtk.SpinButton(0, 5000, 1);
            this.maxDownloadSpeedSpinButton.CanFocus = true;
            this.maxDownloadSpeedSpinButton.Name = "maxDownloadSpeedSpinButton";
            this.maxDownloadSpeedSpinButton.Adjustment.PageIncrement = 10;
            this.maxDownloadSpeedSpinButton.ClimbRate = 1;
            this.maxDownloadSpeedSpinButton.Numeric = true;
            this.table4.Add(this.maxDownloadSpeedSpinButton);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table4[this.maxDownloadSpeedSpinButton]));
            w18.LeftAttach = ((uint)(1));
            w18.RightAttach = ((uint)(2));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.maxUploadSpeedSpinButton = new Gtk.SpinButton(0, 5000, 1);
            this.maxUploadSpeedSpinButton.CanFocus = true;
            this.maxUploadSpeedSpinButton.Name = "maxUploadSpeedSpinButton";
            this.maxUploadSpeedSpinButton.Adjustment.PageIncrement = 10;
            this.maxUploadSpeedSpinButton.ClimbRate = 1;
            this.maxUploadSpeedSpinButton.Numeric = true;
            this.table4.Add(this.maxUploadSpeedSpinButton);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table4[this.maxUploadSpeedSpinButton]));
            w19.TopAttach = ((uint)(1));
            w19.BottomAttach = ((uint)(2));
            w19.LeftAttach = ((uint)(1));
            w19.RightAttach = ((uint)(2));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.uploadSpeedLabel = new Gtk.Label();
            this.uploadSpeedLabel.Name = "uploadSpeedLabel";
            this.uploadSpeedLabel.Xalign = 0F;
            this.uploadSpeedLabel.LabelProp = Mono.Unix.Catalog.GetString("Maximum upload speed: ");
            this.table4.Add(this.uploadSpeedLabel);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table4[this.uploadSpeedLabel]));
            w20.TopAttach = ((uint)(1));
            w20.BottomAttach = ((uint)(2));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment2.Add(this.table4);
            this.frame2.Add(this.GtkAlignment2);
            this.bandwidthPanelLabel = new Gtk.Label();
            this.bandwidthPanelLabel.Name = "bandwidthPanelLabel";
            this.bandwidthPanelLabel.LabelProp = Mono.Unix.Catalog.GetString("<b>Bandwidth</b>");
            this.bandwidthPanelLabel.UseMarkup = true;
            this.frame2.LabelWidget = this.bandwidthPanelLabel;
            this.vbox2.Add(this.frame2);
            Gtk.Box.BoxChild w23 = ((Gtk.Box.BoxChild)(this.vbox2[this.frame2]));
            w23.Position = 1;
            w23.Expand = false;
            w23.Fill = false;
            this.prefNotebook.Add(this.vbox2);
            Gtk.Notebook.NotebookChild w24 = ((Gtk.Notebook.NotebookChild)(this.prefNotebook[this.vbox2]));
            w24.Position = 1;
            // Notebook tab
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Connection");
            this.prefNotebook.SetTabLabel(this.vbox2, this.label3);
            this.label3.ShowAll();
            // Container child prefNotebook.Gtk.Notebook+NotebookChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.frame4 = new Gtk.Frame();
            this.frame4.Name = "frame4";
            this.frame4.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame4.Gtk.Container+ContainerChild
            this.GtkAlignment5 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment5.Name = "GtkAlignment5";
            this.GtkAlignment5.LeftPadding = ((uint)(12));
            // Container child GtkAlignment5.Gtk.Container+ContainerChild
            this.vbox8 = new Gtk.VBox();
            this.vbox8.Name = "vbox8";
            this.vbox8.Spacing = 6;
            // Container child vbox8.Gtk.Box+BoxChild
            this.startNewTorrentsCheckBox = new Gtk.CheckButton();
            this.startNewTorrentsCheckBox.CanFocus = true;
            this.startNewTorrentsCheckBox.Name = "startNewTorrentsCheckBox";
            this.startNewTorrentsCheckBox.Label = Mono.Unix.Catalog.GetString("Start added torrents automatically");
            this.startNewTorrentsCheckBox.Active = true;
            this.startNewTorrentsCheckBox.DrawIndicator = true;
            this.startNewTorrentsCheckBox.UseUnderline = true;
            this.vbox8.Add(this.startNewTorrentsCheckBox);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox8[this.startNewTorrentsCheckBox]));
            w25.Position = 0;
            w25.Expand = false;
            w25.Fill = false;
            this.GtkAlignment5.Add(this.vbox8);
            this.frame4.Add(this.GtkAlignment5);
            this.GtkLabel7 = new Gtk.Label();
            this.GtkLabel7.Name = "GtkLabel7";
            this.GtkLabel7.LabelProp = Mono.Unix.Catalog.GetString("<b>General</b>");
            this.GtkLabel7.UseMarkup = true;
            this.frame4.LabelWidget = this.GtkLabel7;
            this.vbox5.Add(this.frame4);
            Gtk.Box.BoxChild w28 = ((Gtk.Box.BoxChild)(this.vbox5[this.frame4]));
            w28.Position = 0;
            w28.Expand = false;
            w28.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.foldersFrame = new Gtk.Frame();
            this.foldersFrame.Name = "foldersFrame";
            this.foldersFrame.ShadowType = ((Gtk.ShadowType)(0));
            // Container child foldersFrame.Gtk.Container+ContainerChild
            this.GtkAlignment3 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment3.Name = "GtkAlignment3";
            this.GtkAlignment3.LeftPadding = ((uint)(12));
            // Container child GtkAlignment3.Gtk.Container+ContainerChild
            this.foldersTable = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.foldersTable.Name = "foldersTable";
            this.foldersTable.RowSpacing = ((uint)(6));
            this.foldersTable.ColumnSpacing = ((uint)(6));
            // Container child foldersTable.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Default download location: ");
            this.foldersTable.Add(this.label1);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.foldersTable[this.label1]));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child foldersTable.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 0F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Torrent storage location:");
            this.foldersTable.Add(this.label7);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.foldersTable[this.label7]));
            w30.TopAttach = ((uint)(1));
            w30.BottomAttach = ((uint)(2));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            this.GtkAlignment3.Add(this.foldersTable);
            this.foldersFrame.Add(this.GtkAlignment3);
            this.GtkLabel6 = new Gtk.Label();
            this.GtkLabel6.Name = "GtkLabel6";
            this.GtkLabel6.LabelProp = Mono.Unix.Catalog.GetString("<b>Folders</b>");
            this.GtkLabel6.UseMarkup = true;
            this.foldersFrame.LabelWidget = this.GtkLabel6;
            this.vbox5.Add(this.foldersFrame);
            Gtk.Box.BoxChild w33 = ((Gtk.Box.BoxChild)(this.vbox5[this.foldersFrame]));
            w33.Position = 1;
            w33.Expand = false;
            w33.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.frame3 = new Gtk.Frame();
            this.frame3.Name = "frame3";
            this.frame3.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame3.Gtk.Container+ContainerChild
            this.GtkAlignment4 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment4.Name = "GtkAlignment4";
            this.GtkAlignment4.LeftPadding = ((uint)(12));
            // Container child GtkAlignment4.Gtk.Container+ContainerChild
            this.vbox7 = new Gtk.VBox();
            this.vbox7.Name = "vbox7";
            this.vbox7.Spacing = 6;
            // Container child vbox7.Gtk.Box+BoxChild
            this.importTorrentsCheckBox = new Gtk.CheckButton();
            this.importTorrentsCheckBox.CanFocus = true;
            this.importTorrentsCheckBox.Name = "importTorrentsCheckBox";
            this.importTorrentsCheckBox.Label = Mono.Unix.Catalog.GetString("Import new torrents automatically");
            this.importTorrentsCheckBox.DrawIndicator = true;
            this.importTorrentsCheckBox.UseUnderline = true;
            this.vbox7.Add(this.importTorrentsCheckBox);
            Gtk.Box.BoxChild w34 = ((Gtk.Box.BoxChild)(this.vbox7[this.importTorrentsCheckBox]));
            w34.Position = 0;
            w34.Expand = false;
            w34.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.removeOnImportCheckButton = new Gtk.CheckButton();
            this.removeOnImportCheckButton.CanFocus = true;
            this.removeOnImportCheckButton.Name = "removeOnImportCheckButton";
            this.removeOnImportCheckButton.Label = Mono.Unix.Catalog.GetString("Remove torrent file after imported");
            this.removeOnImportCheckButton.DrawIndicator = true;
            this.removeOnImportCheckButton.UseUnderline = true;
            this.vbox7.Add(this.removeOnImportCheckButton);
            Gtk.Box.BoxChild w35 = ((Gtk.Box.BoxChild)(this.vbox7[this.removeOnImportCheckButton]));
            w35.Position = 1;
            w35.Expand = false;
            w35.Fill = false;
            // Container child vbox7.Gtk.Box+BoxChild
            this.importDirectoryHbox = new Gtk.HBox();
            this.importDirectoryHbox.Name = "importDirectoryHbox";
            this.importDirectoryHbox.Spacing = 6;
            // Container child importDirectoryHbox.Gtk.Box+BoxChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Import directory:");
            this.importDirectoryHbox.Add(this.label6);
            Gtk.Box.BoxChild w36 = ((Gtk.Box.BoxChild)(this.importDirectoryHbox[this.label6]));
            w36.Position = 0;
            w36.Expand = false;
            w36.Fill = false;
            this.vbox7.Add(this.importDirectoryHbox);
            Gtk.Box.BoxChild w37 = ((Gtk.Box.BoxChild)(this.vbox7[this.importDirectoryHbox]));
            w37.Position = 2;
            w37.Expand = false;
            w37.Fill = false;
            this.GtkAlignment4.Add(this.vbox7);
            this.frame3.Add(this.GtkAlignment4);
            this.GtkLabel11 = new Gtk.Label();
            this.GtkLabel11.Name = "GtkLabel11";
            this.GtkLabel11.LabelProp = Mono.Unix.Catalog.GetString("<b>Importing Torrents</b>");
            this.GtkLabel11.UseMarkup = true;
            this.frame3.LabelWidget = this.GtkLabel11;
            this.vbox5.Add(this.frame3);
            Gtk.Box.BoxChild w40 = ((Gtk.Box.BoxChild)(this.vbox5[this.frame3]));
            w40.Position = 2;
            w40.Expand = false;
            w40.Fill = false;
            this.prefNotebook.Add(this.vbox5);
            Gtk.Notebook.NotebookChild w41 = ((Gtk.Notebook.NotebookChild)(this.prefNotebook[this.vbox5]));
            w41.Position = 2;
            // Notebook tab
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Downloads");
            this.prefNotebook.SetTabLabel(this.vbox5, this.label4);
            this.label4.ShowAll();
            // Container child prefNotebook.Gtk.Notebook+NotebookChild
            this.vbox9 = new Gtk.VBox();
            this.vbox9.Name = "vbox9";
            this.vbox9.Spacing = 6;
            // Container child vbox9.Gtk.Box+BoxChild
            this.frame5 = new Gtk.Frame();
            this.frame5.Name = "frame5";
            this.frame5.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame5.Gtk.Container+ContainerChild
            this.GtkAlignment6 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment6.Name = "GtkAlignment6";
            this.GtkAlignment6.LeftPadding = ((uint)(12));
            // Container child GtkAlignment6.Gtk.Container+ContainerChild
            this.iconHbox = new Gtk.HBox();
            this.iconHbox.Name = "iconHbox";
            this.iconHbox.Spacing = 6;
            // Container child iconHbox.Gtk.Box+BoxChild
            this.iconEntryBox = new Gtk.HBox();
            this.iconEntryBox.Name = "iconEntryBox";
            this.iconEntryBox.Spacing = 6;
            this.iconHbox.Add(this.iconEntryBox);
            Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.iconHbox[this.iconEntryBox]));
            w42.Position = 0;
            // Container child iconHbox.Gtk.Box+BoxChild
            this.vbox10 = new Gtk.VBox();
            this.vbox10.Name = "vbox10";
            this.vbox10.Spacing = 6;
            // Container child vbox10.Gtk.Box+BoxChild
            this.hbox6 = new Gtk.HBox();
            this.hbox6.Name = "hbox6";
            this.hbox6.Spacing = 6;
            // Container child hbox6.Gtk.Box+BoxChild
            this.nameEntry = new Gtk.Entry();
            this.nameEntry.CanFocus = true;
            this.nameEntry.Name = "nameEntry";
            this.nameEntry.IsEditable = true;
            this.nameEntry.InvisibleChar = '●';
            this.hbox6.Add(this.nameEntry);
            Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(this.hbox6[this.nameEntry]));
            w43.PackType = ((Gtk.PackType)(1));
            w43.Position = 0;
            // Container child hbox6.Gtk.Box+BoxChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.hbox6.Add(this.label8);
            Gtk.Box.BoxChild w44 = ((Gtk.Box.BoxChild)(this.hbox6[this.label8]));
            w44.PackType = ((Gtk.PackType)(1));
            w44.Position = 1;
            w44.Expand = false;
            w44.Fill = false;
            this.vbox10.Add(this.hbox6);
            Gtk.Box.BoxChild w45 = ((Gtk.Box.BoxChild)(this.vbox10[this.hbox6]));
            w45.Position = 0;
            w45.Expand = false;
            w45.Fill = false;
            this.iconHbox.Add(this.vbox10);
            Gtk.Box.BoxChild w46 = ((Gtk.Box.BoxChild)(this.iconHbox[this.vbox10]));
            w46.Position = 1;
            // Container child iconHbox.Gtk.Box+BoxChild
            this.vbox12 = new Gtk.VBox();
            this.vbox12.Name = "vbox12";
            this.vbox12.Spacing = 6;
            this.iconHbox.Add(this.vbox12);
            Gtk.Box.BoxChild w47 = ((Gtk.Box.BoxChild)(this.iconHbox[this.vbox12]));
            w47.Position = 2;
            this.GtkAlignment6.Add(this.iconHbox);
            this.frame5.Add(this.GtkAlignment6);
            this.GtkLabel12 = new Gtk.Label();
            this.GtkLabel12.Name = "GtkLabel12";
            this.GtkLabel12.LabelProp = Mono.Unix.Catalog.GetString("<b>Create a label</b>");
            this.GtkLabel12.UseMarkup = true;
            this.frame5.LabelWidget = this.GtkLabel12;
            this.vbox9.Add(this.frame5);
            Gtk.Box.BoxChild w50 = ((Gtk.Box.BoxChild)(this.vbox9[this.frame5]));
            w50.Position = 0;
            w50.Expand = false;
            w50.Fill = false;
            // Container child vbox9.Gtk.Box+BoxChild
            this.frame6 = new Gtk.Frame();
            this.frame6.Name = "frame6";
            this.frame6.ShadowType = ((Gtk.ShadowType)(0));
            // Container child frame6.Gtk.Container+ContainerChild
            this.GtkAlignment7 = new Gtk.Alignment(0F, 0F, 1F, 1F);
            this.GtkAlignment7.Name = "GtkAlignment7";
            this.GtkAlignment7.LeftPadding = ((uint)(12));
            // Container child GtkAlignment7.Gtk.Container+ContainerChild
            this.hbox8 = new Gtk.HBox();
            this.hbox8.Name = "hbox8";
            this.hbox8.Spacing = 6;
            // Container child hbox8.Gtk.Box+BoxChild
            this.labelScrolledWindow = new Gtk.ScrolledWindow();
            this.labelScrolledWindow.CanFocus = true;
            this.labelScrolledWindow.Name = "labelScrolledWindow";
            this.labelScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            this.hbox8.Add(this.labelScrolledWindow);
            Gtk.Box.BoxChild w51 = ((Gtk.Box.BoxChild)(this.hbox8[this.labelScrolledWindow]));
            w51.Position = 0;
            // Container child hbox8.Gtk.Box+BoxChild
            this.vbox11 = new Gtk.VBox();
            this.vbox11.Name = "vbox11";
            this.vbox11.Spacing = 6;
            // Container child vbox11.Gtk.Box+BoxChild
            this.addLabelButton = new Gtk.Button();
            this.addLabelButton.Sensitive = false;
            this.addLabelButton.CanFocus = true;
            this.addLabelButton.Name = "addLabelButton";
            this.addLabelButton.UseUnderline = true;
            // Container child addLabelButton.Gtk.Container+ContainerChild
            Gtk.Alignment w52 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w53 = new Gtk.HBox();
            w53.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w54 = new Gtk.Image();
            w54.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-add", Gtk.IconSize.Menu, 16);
            w53.Add(w54);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w56 = new Gtk.Label();
            w56.LabelProp = Mono.Unix.Catalog.GetString("Add");
            w56.UseUnderline = true;
            w53.Add(w56);
            w52.Add(w53);
            this.addLabelButton.Add(w52);
            this.vbox11.Add(this.addLabelButton);
            Gtk.Box.BoxChild w60 = ((Gtk.Box.BoxChild)(this.vbox11[this.addLabelButton]));
            w60.Position = 0;
            w60.Expand = false;
            w60.Fill = false;
            // Container child vbox11.Gtk.Box+BoxChild
            this.removeLabelButton = new Gtk.Button();
            this.removeLabelButton.Sensitive = false;
            this.removeLabelButton.CanFocus = true;
            this.removeLabelButton.Name = "removeLabelButton";
            this.removeLabelButton.UseUnderline = true;
            // Container child removeLabelButton.Gtk.Container+ContainerChild
            Gtk.Alignment w61 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment8.Gtk.Container+ContainerChild
            Gtk.HBox w62 = new Gtk.HBox();
            w62.Spacing = 2;
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Image w63 = new Gtk.Image();
            w63.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-remove", Gtk.IconSize.Menu, 16);
            w62.Add(w63);
            // Container child GtkHBox1.Gtk.Container+ContainerChild
            Gtk.Label w65 = new Gtk.Label();
            w65.LabelProp = Mono.Unix.Catalog.GetString("Remove");
            w65.UseUnderline = true;
            w62.Add(w65);
            w61.Add(w62);
            this.removeLabelButton.Add(w61);
            this.vbox11.Add(this.removeLabelButton);
            Gtk.Box.BoxChild w69 = ((Gtk.Box.BoxChild)(this.vbox11[this.removeLabelButton]));
            w69.Position = 1;
            w69.Expand = false;
            w69.Fill = false;
            this.hbox8.Add(this.vbox11);
            Gtk.Box.BoxChild w70 = ((Gtk.Box.BoxChild)(this.hbox8[this.vbox11]));
            w70.Position = 1;
            w70.Expand = false;
            w70.Fill = false;
            this.GtkAlignment7.Add(this.hbox8);
            this.frame6.Add(this.GtkAlignment7);
            this.GtkLabel15 = new Gtk.Label();
            this.GtkLabel15.Name = "GtkLabel15";
            this.GtkLabel15.LabelProp = Mono.Unix.Catalog.GetString("<b>Manage labels</b>");
            this.GtkLabel15.UseMarkup = true;
            this.frame6.LabelWidget = this.GtkLabel15;
            this.vbox9.Add(this.frame6);
            Gtk.Box.BoxChild w73 = ((Gtk.Box.BoxChild)(this.vbox9[this.frame6]));
            w73.Position = 1;
            this.prefNotebook.Add(this.vbox9);
            Gtk.Notebook.NotebookChild w74 = ((Gtk.Notebook.NotebookChild)(this.prefNotebook[this.vbox9]));
            w74.Position = 3;
            // Notebook tab
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Labels");
            this.prefNotebook.SetTabLabel(this.vbox9, this.label5);
            this.label5.ShowAll();
            w1.Add(this.prefNotebook);
            Gtk.Box.BoxChild w75 = ((Gtk.Box.BoxChild)(w1[this.prefNotebook]));
            w75.Position = 0;
            // Internal child Monsoon.PreferencesDialog.ActionArea
            Gtk.HButtonBox w76 = this.ActionArea;
            w76.Name = "GtkDialog_ActionArea";
            w76.Spacing = 6;
            w76.BorderWidth = ((uint)(5));
            w76.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child GtkDialog_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.button478 = new Gtk.Button();
            this.button478.CanDefault = true;
            this.button478.CanFocus = true;
            this.button478.Name = "button478";
            this.button478.UseStock = true;
            this.button478.UseUnderline = true;
            this.button478.Label = "gtk-close";
            this.AddActionWidget(this.button478, -7);
            Gtk.ButtonBox.ButtonBoxChild w77 = ((Gtk.ButtonBox.ButtonBoxChild)(w76[this.button478]));
            w77.Expand = false;
            w77.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 423;
            this.Show();
            this.portSpinButton.ValueChanged += new System.EventHandler(this.OnPortSpinButtonValueChanged);
            this.maxConnectionsSpinButton.ValueChanged += new System.EventHandler(this.OnMaxConnectionsSpinButtonValueChanged);
            this.maxUploadSpeedSpinButton.ValueChanged += new System.EventHandler(this.OnMaxUploadSpeedSpinButtonValueChanged);
            this.maxDownloadSpeedSpinButton.ValueChanged += new System.EventHandler(this.OnMaxDownloadSpeedSpinButtonValueChanged);
            this.startNewTorrentsCheckBox.Clicked += new System.EventHandler(this.OnStartNewTorrentsCheckBoxClicked);
            this.importTorrentsCheckBox.Clicked += new System.EventHandler(this.OnImportTorrentsCheckBoxClicked);
            this.removeOnImportCheckButton.Clicked += new System.EventHandler(this.OnRemoveOnImportCheckButtonClicked);
            this.nameEntry.Changed += new System.EventHandler(this.OnNameEntryChanged);
            this.addLabelButton.Clicked += new System.EventHandler(this.OnAddLabelButtonClicked);
            this.removeLabelButton.Clicked += new System.EventHandler(this.OnRemoveLabelButtonClicked);
        }
    }
}
