// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monsoon {
    
    
    public partial class DruidConnectionPage {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Label label1;
        
        private Gtk.Table table1;
        
        private Gtk.SpinButton downSpinButton;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.SpinButton portSpinButton;
        
        private Gtk.CheckButton upnpCheckButton;
        
        private Gtk.SpinButton upSpinButton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Monsoon.DruidConnectionPage
            Stetic.BinContainer.Attach(this);
            this.Name = "Monsoon.DruidConnectionPage";
            // Container child Monsoon.DruidConnectionPage.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("To ensure that MonoTorrent opperates as fast as possible you must configure what port to use.");
            this.label1.Wrap = true;
            this.vbox2.Add(this.label1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox2[this.label1]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(5)), ((uint)(3)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            this.table1.BorderWidth = ((uint)(5));
            // Container child table1.Gtk.Table+TableChild
            this.downSpinButton = new Gtk.SpinButton(0, 100, 1);
            this.downSpinButton.CanFocus = true;
            this.downSpinButton.Name = "downSpinButton";
            this.downSpinButton.Adjustment.PageIncrement = 10;
            this.downSpinButton.ClimbRate = 1;
            this.downSpinButton.Numeric = true;
            this.table1.Add(this.downSpinButton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.downSpinButton]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 0F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("Listen Port:");
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 0F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("Maximum upload speed:");
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w4.TopAttach = ((uint)(3));
            w4.BottomAttach = ((uint)(4));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 0F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Maximum download speed:");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w5.TopAttach = ((uint)(2));
            w5.BottomAttach = ((uint)(3));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.portSpinButton = new Gtk.SpinButton(0, 65535, 1);
            this.portSpinButton.CanFocus = true;
            this.portSpinButton.Name = "portSpinButton";
            this.portSpinButton.Adjustment.PageIncrement = 10;
            this.portSpinButton.ClimbRate = 1;
            this.portSpinButton.Numeric = true;
            this.portSpinButton.Value = 6767;
            this.table1.Add(this.portSpinButton);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.portSpinButton]));
            w6.LeftAttach = ((uint)(1));
            w6.RightAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.upnpCheckButton = new Gtk.CheckButton();
            this.upnpCheckButton.CanFocus = true;
            this.upnpCheckButton.Name = "upnpCheckButton";
            this.upnpCheckButton.Label = Mono.Unix.Catalog.GetString("Enable UPnP");
            this.upnpCheckButton.DrawIndicator = true;
            this.upnpCheckButton.UseUnderline = true;
            this.upnpCheckButton.Xalign = 0F;
            this.table1.Add(this.upnpCheckButton);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.upnpCheckButton]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.RightAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.upSpinButton = new Gtk.SpinButton(0, 100, 1);
            this.upSpinButton.CanFocus = true;
            this.upSpinButton.Name = "upSpinButton";
            this.upSpinButton.Adjustment.PageIncrement = 10;
            this.upSpinButton.ClimbRate = 1;
            this.upSpinButton.Numeric = true;
            this.table1.Add(this.upSpinButton);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.upSpinButton]));
            w8.TopAttach = ((uint)(3));
            w8.BottomAttach = ((uint)(4));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w9.Position = 1;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
